// Large seed arrays — vehicles, customers, estimates, leads, etc.

export const VEHICLES = [
  {
    id: 'v001', customerId: 'c001',
    year: 2023, make: 'Tesla',      model: 'Model 3',       trim: 'Long Range',
    vin: '5YJ3E1EA1PF123456', type: 'sedan',   color: 'Midnight Silver',
    length_mm: 4694, width_mm: 1849, height_mm: 1443, curb_weight_kg: 1752,
    wrapStatus: 'wrapped', wrapColor: 'Matte Charcoal', tags: ['VIP'],
    estimateCount: 2, lastServiceAt: '2024-11-15T10:00:00Z', createdAt: '2024-01-10T09:00:00Z',
    notes: 'Full body matte wrap + ceramic coat. Handle charge port area carefully.',
  },
  {
    id: 'v002', customerId: 'c002',
    year: 2022, make: 'BMW',        model: 'M4',            trim: 'Competition',
    vin: 'WBS43AY01NCK98765', type: 'coupe',   color: 'Brooklyn Grey',
    length_mm: 4794, width_mm: 1887, height_mm: 1393, curb_weight_kg: 1730,
    wrapStatus: 'scheduled', wrapColor: 'Satin Black', tags: [],
    estimateCount: 1, lastServiceAt: null, createdAt: '2024-02-14T11:00:00Z',
    notes: 'Customer wants full satin black. Schedule confirmed for next sprint.',
  },
  {
    id: 'v003', customerId: 'c003',
    year: 2021, make: 'Ford',       model: 'F-150 Raptor',  trim: 'SuperCrew',
    vin: '1FTFW1RG9MFC87321', type: 'truck',   color: 'Shadow Black',
    length_mm: 5921, width_mm: 2189, height_mm: 1928, curb_weight_kg: 2336,
    wrapStatus: 'partial', wrapColor: 'Gloss White Roof', tags: ['Repeat'],
    estimateCount: 3, lastServiceAt: '2024-09-03T14:00:00Z', createdAt: '2023-06-01T08:00:00Z',
    notes: 'Partial roof + hood. Previous full wrap removed — surface in good condition.',
  },
  {
    id: 'v004', customerId: 'c004',
    year: 2024, make: 'Porsche',    model: '911',           trim: 'Carrera S',
    vin: 'WP0AB2A99RS234567', type: 'sports',  color: 'Guards Red',
    length_mm: 4519, width_mm: 1852, height_mm: 1300, curb_weight_kg: 1452,
    wrapStatus: 'wrapped', wrapColor: 'Chrome Gold', tags: ['VIP'],
    estimateCount: 2, lastServiceAt: '2025-01-20T09:00:00Z', createdAt: '2024-03-05T10:00:00Z',
    notes: 'Full chrome wrap. Extremely careful around door handles and hood strakes.',
  },
  {
    id: 'v005', customerId: 'c005',
    year: 2020, make: 'Jeep',       model: 'Wrangler',      trim: 'Rubicon',
    vin: '1C4HJXFG5LW512098', type: 'suv',     color: 'Sting-Gray',
    length_mm: 4330, width_mm: 1893, height_mm: 1848, curb_weight_kg: 1800,
    wrapStatus: 'wrapped', wrapColor: 'Military Green', tags: [],
    estimateCount: 1, lastServiceAt: '2024-07-12T11:00:00Z', createdAt: '2023-11-20T09:00:00Z',
    notes: 'Off-road use. Extra laminate on lower rocker panels.',
  },
  {
    id: 'v006', customerId: 'c006',
    year: 2023, make: 'Chevrolet',  model: 'Silverado 1500', trim: 'LTZ',
    vin: '1GCUDEED7PZ654321', type: 'truck',   color: 'Summit White',
    length_mm: 5836, width_mm: 2031, height_mm: 1894, curb_weight_kg: 2018,
    wrapStatus: 'partial', wrapColor: 'Brushed Steel Hood', tags: ['Fleet'],
    estimateCount: 4, lastServiceAt: '2024-12-01T08:00:00Z', createdAt: '2023-03-15T09:00:00Z',
    notes: 'Fleet vehicle. 3 more units queued. Hood + cab partial.',
  },
  {
    id: 'v007', customerId: 'c007',
    year: 2022, make: 'Land Rover', model: 'Range Rover Sport', trim: 'HSE',
    vin: 'SALWR2RV7NA456789', type: 'luxury',  color: 'Santorini Black',
    length_mm: 4879, width_mm: 2073, height_mm: 1780, curb_weight_kg: 2265,
    wrapStatus: 'wrapped', wrapColor: 'Midnight Blue', tags: ['VIP', 'Repeat'],
    estimateCount: 3, lastServiceAt: '2025-02-10T10:00:00Z', createdAt: '2022-09-01T09:00:00Z',
    notes: 'Second full wrap for this customer. Previous: gloss black. Now midnight blue.',
  },
  {
    id: 'v008', customerId: 'c008',
    year: 2021, make: 'Lamborghini', model: 'Urus',          trim: 'Pearl Capsule',
    vin: 'ZPBUA1ZL1MLA12345', type: 'luxury',  color: 'Arancio Borealis',
    length_mm: 5112, width_mm: 2016, height_mm: 1638, curb_weight_kg: 2197,
    wrapStatus: 'wrapped', wrapColor: 'Stealth PPF + Ceramic', tags: ['VIP'],
    estimateCount: 2, lastServiceAt: '2025-03-01T10:00:00Z', createdAt: '2024-02-01T09:00:00Z',
    notes: 'Full PPF stealth + ceramic coat. High-value asset — assign senior installer.',
  },
  {
    id: 'v009', customerId: 'c009',
    year: 2023, make: 'Mercedes-Benz', model: 'G 63 AMG',   trim: 'AMG',
    vin: 'WDCYC7HF3PX987654', type: 'luxury',  color: 'Obsidian Black',
    length_mm: 4966, width_mm: 1931, height_mm: 1969, curb_weight_kg: 2560,
    wrapStatus: 'wrapped', wrapColor: 'Two-Tone Matte/Gloss', tags: ['VIP', 'Corporate'],
    estimateCount: 1, lastServiceAt: '2025-01-10T11:00:00Z', createdAt: '2024-08-15T09:00:00Z',
    notes: 'Custom two-tone split. Upper half matte, lower gloss. Alignment critical.',
  },
  {
    id: 'v010', customerId: 'c010',
    year: 2024, make: 'Toyota',     model: 'GR Supra',      trim: 'A91-MT',
    vin: 'WZ1DB4C07R2012345', type: 'sports',  color: 'Refraction',
    length_mm: 4380, width_mm: 1865, height_mm: 1294, curb_weight_kg: 1495,
    wrapStatus: 'bare', wrapColor: null, tags: [],
    estimateCount: 1, lastServiceAt: null, createdAt: '2025-01-05T09:00:00Z',
    notes: 'New car. Customer wants full matte black — awaiting deposit.',
  },
  {
    id: 'v011', customerId: 'c011',
    year: 2022, make: 'Dodge',      model: 'Challenger',    trim: 'SRT Hellcat',
    vin: '2C3CDZL92NH234567', type: 'coupe',   color: 'Pitch Black',
    length_mm: 5031, width_mm: 1897, height_mm: 1396, curb_weight_kg: 1840,
    wrapStatus: 'wrapped', wrapColor: 'Candy Red', tags: ['Repeat'],
    estimateCount: 2, lastServiceAt: '2024-10-05T09:00:00Z', createdAt: '2023-04-22T08:00:00Z',
    notes: 'Candy Red full wrap with gloss black accents. Previous: satin orange.',
  },
  {
    id: 'v012', customerId: 'c012',
    year: 2023, make: 'Audi',       model: 'RS6 Avant',     trim: 'RS6',
    vin: 'WAUZZZ4G5PN345678', type: 'sedan',   color: 'Nardo Gray',
    length_mm: 5060, width_mm: 1951, height_mm: 1478, curb_weight_kg: 2075,
    wrapStatus: 'wrapped', wrapColor: 'Satin Blue Frost', tags: ['VIP'],
    estimateCount: 2, lastServiceAt: '2024-11-22T10:00:00Z', createdAt: '2023-09-10T09:00:00Z',
    notes: 'Satin Blue Frost full wrap. Customer is detail-obsessed — document every panel.',
  },
  // Additional vehicles for variety
  {
    id: 'v013', customerId: 'c013',
    year: 2023, make: 'Ford',       model: 'Mustang GT500', trim: 'Shelby',
    vin: '1FA6P8SJ1P5500123', type: 'coupe',   color: 'Oxford White',
    length_mm: 4786, width_mm: 1916, height_mm: 1394, curb_weight_kg: 1795,
    wrapStatus: 'wrapped', wrapColor: 'Matte Blue + Racing Stripes', tags: ['Repeat'],
    estimateCount: 3, lastServiceAt: '2025-02-15T09:00:00Z', createdAt: '2022-12-01T09:00:00Z',
    notes: 'GT500 stripes + full body matte blue. Customer races regionally.',
  },
  {
    id: 'v014', customerId: 'c013',
    year: 2021, make: 'Porsche',    model: 'Cayenne',       trim: 'GTS',
    vin: 'WP1AG2AY8MDA67890', type: 'suv',     color: 'Crayon',
    length_mm: 4926, width_mm: 1983, height_mm: 1696, curb_weight_kg: 2010,
    wrapStatus: 'partial', wrapColor: 'Gloss Black Trim', tags: [],
    estimateCount: 1, lastServiceAt: '2024-06-01T10:00:00Z', createdAt: '2023-02-10T09:00:00Z',
    notes: 'Trim accent wrap only. Bright orange kept — partial blackout package.',
  },
  {
    id: 'v015', customerId: 'c014',
    year: 2022, make: 'Ram',        model: '1500 TRX',      trim: 'Launch Edition',
    vin: '1C6SRFU98NN456789', type: 'truck',   color: 'Baja Yellow',
    length_mm: 5893, width_mm: 2109, height_mm: 1984, curb_weight_kg: 2643,
    wrapStatus: 'wrapped', wrapColor: 'Gloss White + Black Accents', tags: ['Fleet'],
    estimateCount: 2, lastServiceAt: '2025-01-28T10:00:00Z', createdAt: '2024-04-01T09:00:00Z',
    notes: 'Part of a 4-truck fleet wrap. Gloss white body, matte black hood + bed.',
  },
  {
    id: 'v016', customerId: 'c014',
    year: 2022, make: 'Ram',        model: '1500 TRX',      trim: 'Launch Edition',
    vin: '1C6SRFU98NN456790', type: 'truck',   color: 'Baja Yellow',
    length_mm: 5893, width_mm: 2109, height_mm: 1984, curb_weight_kg: 2643,
    wrapStatus: 'wrapped', wrapColor: 'Gloss White + Black Accents', tags: ['Fleet'],
    estimateCount: 1, lastServiceAt: '2025-01-28T10:00:00Z', createdAt: '2024-04-01T09:00:00Z',
    notes: 'Fleet unit #2 of 4.',
  },
  {
    id: 'v017', customerId: 'c015',
    year: 2024, make: 'Rivian',     model: 'R1T',           trim: 'Adventure',
    vin: '7FCTGAAA3PN123789', type: 'truck',   color: 'El Cap Granite',
    length_mm: 5485, width_mm: 2077, height_mm: 1803, curb_weight_kg: 2676,
    wrapStatus: 'scheduled', wrapColor: 'Matte Earth Tone', tags: ['New'],
    estimateCount: 1, lastServiceAt: null, createdAt: '2025-03-10T09:00:00Z',
    notes: 'Brand new Rivian. Rust-prevention film + full matte earth wrap scheduled.',
  },
  {
    id: 'v018', customerId: 'c016',
    year: 2020, make: 'Tesla',      model: 'Model X',       trim: 'Long Range',
    vin: '5YJXCDE21LF567890', type: 'suv',     color: 'Pearl White',
    length_mm: 5037, width_mm: 1999, height_mm: 1684, curb_weight_kg: 2459,
    wrapStatus: 'wrapped', wrapColor: 'Satin Rose Gold', tags: ['VIP', 'Repeat'],
    estimateCount: 4, lastServiceAt: '2025-02-20T11:00:00Z', createdAt: '2021-03-01T09:00:00Z',
    notes: 'Long-standing customer. Rose gold full wrap renewed annually.',
  },
  {
    id: 'v019', customerId: 'c016',
    year: 2023, make: 'Tesla',      model: 'Cybertruck',    trim: 'AWD',
    vin: '7G2CECEA0PF789012', type: 'truck',   color: 'Stainless Steel',
    length_mm: 5885, width_mm: 2100, height_mm: 1905, curb_weight_kg: 2995,
    wrapStatus: 'bare', wrapColor: null, tags: ['VIP', 'New'],
    estimateCount: 1, lastServiceAt: null, createdAt: '2025-03-20T09:00:00Z',
    notes: 'Stainless exterior — special prep required before any wrap attempt. Awaiting quote.',
  },
  {
    id: 'v020', customerId: 'c017',
    year: 2023, make: 'Mercedes-Benz', model: 'Sprinter',   trim: '2500',
    vin: 'W1Y40CHY7PT123456', type: 'van',     color: 'Arctic White',
    length_mm: 7340, width_mm: 1993, height_mm: 2715, curb_weight_kg: 2260,
    wrapStatus: 'wrapped', wrapColor: 'Full Custom Brand Wrap', tags: ['Corporate', 'Fleet'],
    estimateCount: 5, lastServiceAt: '2025-01-05T08:00:00Z', createdAt: '2022-06-01T09:00:00Z',
    notes: 'Fleet of 6 Sprinters. Custom brand livery for local delivery company.',
  },
  {
    id: 'v021', customerId: 'c017',
    year: 2023, make: 'Mercedes-Benz', model: 'Sprinter',   trim: '2500',
    vin: 'W1Y40CHY7PT123457', type: 'van',     color: 'Arctic White',
    length_mm: 7340, width_mm: 1993, height_mm: 2715, curb_weight_kg: 2260,
    wrapStatus: 'wrapped', wrapColor: 'Full Custom Brand Wrap', tags: ['Corporate', 'Fleet'],
    estimateCount: 1, lastServiceAt: '2025-01-05T08:00:00Z', createdAt: '2022-06-01T09:00:00Z',
    notes: 'Fleet unit #2. Brand livery.',
  },
  {
    id: 'v022', customerId: 'c018',
    year: 2024, make: 'Honda',      model: 'Civic Type R',  trim: 'Type R',
    vin: 'SHHFK8G63RE001234', type: 'hatchback', color: 'Championship White',
    length_mm: 4589, width_mm: 1986, height_mm: 1396, curb_weight_kg: 1429,
    wrapStatus: 'partial', wrapColor: 'Carbon Fiber Vinyl Accents', tags: [],
    estimateCount: 1, lastServiceAt: '2024-11-10T09:00:00Z', createdAt: '2024-09-01T09:00:00Z',
    notes: 'Carbon fiber vinyl roof, mirrors, and rear diffuser area.',
  },
  {
    id: 'v023', customerId: 'c019',
    year: 2022, make: 'Cadillac',   model: 'Escalade',      trim: 'Sport Platinum',
    vin: '1GYS4PKL5NR234567', type: 'luxury',  color: 'Shadow Metallic',
    length_mm: 5383, width_mm: 2087, height_mm: 1938, curb_weight_kg: 2640,
    wrapStatus: 'wrapped', wrapColor: 'Gloss Black Full Blackout', tags: ['VIP', 'Corporate'],
    estimateCount: 2, lastServiceAt: '2024-12-15T09:00:00Z', createdAt: '2023-07-01T09:00:00Z',
    notes: 'Full blackout — all chrome deleted via gloss black vinyl. Executive vehicle.',
  },
  {
    id: 'v024', customerId: 'c020',
    year: 2021, make: 'Subaru',     model: 'WRX STI',       trim: 'Limited',
    vin: 'JF1VA2V67M9876543', type: 'sedan',   color: 'WR Blue Pearl',
    length_mm: 4597, width_mm: 1795, height_mm: 1470, curb_weight_kg: 1517,
    wrapStatus: 'wrapped', wrapColor: 'Matte Rally Red', tags: [],
    estimateCount: 2, lastServiceAt: '2024-08-20T09:00:00Z', createdAt: '2023-01-15T09:00:00Z',
    notes: 'Rally-inspired matte red. Customer requested track-safe materials.',
  },
];

export const CUSTOMERS = [
  {
    id: 'c001', name: 'Marcus Bell',
    phone: '(310) 555-0142', email: 'marcus.bell@gmail.com',
    company: null, address: { street: '2241 Sunset Blvd', city: 'Los Angeles', state: 'CA', zip: '90026' },
    tags: ['VIP', 'Repeat'], source: 'referral', assignee: 'Alex R.',
    vehicleIds: ['v001'],
    estimateCount: 2, totalSpent: 8400, lifetimeValue: 12000,
    lastActivityAt: '2024-11-15T10:00:00Z', createdAt: '2024-01-10T09:00:00Z',
    status: 'active',
    notes: 'High-value repeat customer. Referred 3 clients. Always pays on deposit day.',
    activities: [
      { type: 'estimate', text: 'New estimate created — Tesla Model 3 full wrap', at: '2024-11-01T09:00:00Z' },
      { type: 'payment', text: 'Deposit received — $1,800', at: '2024-11-03T14:00:00Z' },
      { type: 'job', text: 'Job completed — Matte Charcoal wrap', at: '2024-11-15T10:00:00Z' },
    ],
  },
  {
    id: 'c002', name: 'Priya Nair',
    phone: '(415) 555-0267', email: 'priya.nair@outlook.com',
    company: null, address: { street: '880 Valencia St', city: 'San Francisco', state: 'CA', zip: '94110' },
    tags: ['New'], source: 'instagram', assignee: 'Jamie K.',
    vehicleIds: ['v002'],
    estimateCount: 1, totalSpent: 0, lifetimeValue: 5600,
    lastActivityAt: '2024-02-14T11:00:00Z', createdAt: '2024-02-14T11:00:00Z',
    status: 'active',
    notes: 'Found us through Instagram. Excited about the satin black look. Awaiting deposit.',
    activities: [
      { type: 'lead', text: 'Lead received via Instagram DM', at: '2024-02-10T08:00:00Z' },
      { type: 'estimate', text: 'Estimate sent — BMW M4 satin black', at: '2024-02-14T11:00:00Z' },
    ],
  },
  {
    id: 'c003', name: 'Jordan Cole',
    phone: '(512) 555-0388', email: 'jordan.cole@protonmail.com',
    company: 'Cole Offroad LLC', address: { street: '1500 E 6th St', city: 'Austin', state: 'TX', zip: '78702' },
    tags: ['Repeat', 'Referral'], source: 'referral', assignee: 'Sam T.',
    vehicleIds: ['v003'],
    estimateCount: 3, totalSpent: 14200, lifetimeValue: 18000,
    lastActivityAt: '2024-09-03T14:00:00Z', createdAt: '2023-06-01T08:00:00Z',
    status: 'active',
    notes: 'Truck enthusiast. Runs an offroad parts shop. Sends us at least 2 referrals/yr.',
    activities: [
      { type: 'job', text: 'Partial wrap completed — Gloss White Roof', at: '2024-09-03T14:00:00Z' },
      { type: 'estimate', text: 'Estimate approved — rocker panel film', at: '2024-08-20T09:00:00Z' },
      { type: 'referral', text: 'Referred client: Devon Walsh', at: '2024-07-01T09:00:00Z' },
    ],
  },
  {
    id: 'c004', name: 'Remi Santos',
    phone: '(305) 555-0199', email: 'remi@remisantos.com',
    company: 'Santos Imports', address: { street: '1000 Brickell Ave', city: 'Miami', state: 'FL', zip: '33131' },
    tags: ['VIP', 'Corporate'], source: 'website', assignee: 'Alex R.',
    vehicleIds: ['v004'],
    estimateCount: 2, totalSpent: 19800, lifetimeValue: 30000,
    lastActivityAt: '2025-01-20T09:00:00Z', createdAt: '2024-03-05T10:00:00Z',
    status: 'active',
    notes: 'Car importer. Pays upfront, no negotiation. Expects white-glove treatment.',
    activities: [
      { type: 'job', text: 'Job completed — Porsche 911 Chrome Gold wrap', at: '2025-01-20T09:00:00Z' },
      { type: 'payment', text: 'Full payment received — $9,400', at: '2025-01-20T10:00:00Z' },
    ],
  },
  {
    id: 'c005', name: 'Aisha Owens',
    phone: '(720) 555-0321', email: 'aisha.owens@icloud.com',
    company: null, address: { street: '500 16th St Mall', city: 'Denver', state: 'CO', zip: '80202' },
    tags: [], source: 'google', assignee: 'Morgan L.',
    vehicleIds: ['v005'],
    estimateCount: 1, totalSpent: 4100, lifetimeValue: 4100,
    lastActivityAt: '2024-07-12T11:00:00Z', createdAt: '2023-11-20T09:00:00Z',
    status: 'active',
    notes: 'Happy with military green wrap. Left 5-star review on Google.',
    activities: [
      { type: 'job', text: 'Job completed — Jeep Wrangler military green', at: '2024-07-12T11:00:00Z' },
      { type: 'review', text: 'Google review posted — 5 stars', at: '2024-07-15T09:00:00Z' },
    ],
  },
  {
    id: 'c006', name: 'Kyle Huang',
    phone: '(312) 555-0456', email: 'kyle.huang@gmail.com',
    company: 'Huang Logistics', address: { street: '333 N Michigan Ave', city: 'Chicago', state: 'IL', zip: '60601' },
    tags: ['Fleet', 'Corporate', 'Repeat'], source: 'referral', assignee: 'Sam T.',
    vehicleIds: ['v006'],
    estimateCount: 4, totalSpent: 22400, lifetimeValue: 40000,
    lastActivityAt: '2024-12-01T08:00:00Z', createdAt: '2023-03-15T09:00:00Z',
    status: 'active',
    notes: 'Fleet manager for 12-truck logistics company. Best fleet account. Pays NET-30.',
    activities: [
      { type: 'job', text: 'Fleet unit #4 completed — Silverado partial wrap', at: '2024-12-01T08:00:00Z' },
      { type: 'estimate', text: 'Batch estimate approved — 2 more units', at: '2024-11-15T09:00:00Z' },
    ],
  },
  {
    id: 'c007', name: 'Tina Marsh',
    phone: '(929) 555-0571', email: 'tina.marsh@gmail.com',
    company: null, address: { street: '42 W 72nd St', city: 'New York', state: 'NY', zip: '10023' },
    tags: ['VIP', 'Repeat'], source: 'instagram', assignee: 'Alex R.',
    vehicleIds: ['v007'],
    estimateCount: 3, totalSpent: 33600, lifetimeValue: 45000,
    lastActivityAt: '2025-02-10T10:00:00Z', createdAt: '2022-09-01T09:00:00Z',
    status: 'active',
    notes: 'Interior designer. Obsessed with color. Comes back every 18 months for new look.',
    activities: [
      { type: 'job', text: 'Job completed — Range Rover Sport midnight blue', at: '2025-02-10T10:00:00Z' },
      { type: 'note', text: 'Customer mentioned next wrap idea: deep burgundy', at: '2025-02-10T11:00:00Z' },
    ],
  },
  {
    id: 'c008', name: 'Devon Walsh',
    phone: '(424) 555-0692', email: 'dwalsh@walshgroup.io',
    company: 'Walsh Group', address: { street: '9000 Wilshire Blvd', city: 'Beverly Hills', state: 'CA', zip: '90210' },
    tags: ['VIP', 'Corporate'], source: 'referral', assignee: 'Alex R.',
    vehicleIds: ['v008'],
    estimateCount: 2, totalSpent: 29600, lifetimeValue: 35000,
    lastActivityAt: '2025-03-01T10:00:00Z', createdAt: '2024-02-01T09:00:00Z',
    status: 'active',
    notes: 'Private equity. Referred by Jordan Cole. Extremely high expectations. Tip well.',
    activities: [
      { type: 'job', text: 'PPF stealth + ceramic coat completed — Lamborghini Urus', at: '2025-03-01T10:00:00Z' },
      { type: 'payment', text: 'Final balance paid — $14,800', at: '2025-03-01T14:00:00Z' },
    ],
  },
  {
    id: 'c009', name: 'Carla Reyes',
    phone: '(786) 555-0813', email: 'carla.reyes@gmail.com',
    company: 'CR Media Group', address: { street: '700 Brickell Ave', city: 'Miami', state: 'FL', zip: '33131' },
    tags: ['Corporate', 'VIP'], source: 'website', assignee: 'Jamie K.',
    vehicleIds: ['v009'],
    estimateCount: 1, totalSpent: 13500, lifetimeValue: 13500,
    lastActivityAt: '2025-01-10T11:00:00Z', createdAt: '2024-08-15T09:00:00Z',
    status: 'active',
    notes: 'Media exec. Car is used for client transportation — always needs to look pristine.',
    activities: [
      { type: 'job', text: 'Job completed — G63 two-tone matte/gloss wrap', at: '2025-01-10T11:00:00Z' },
    ],
  },
  {
    id: 'c010', name: "Finn O'Brien",
    phone: '(617) 555-0934', email: 'finn.obrien@me.com',
    company: null, address: { street: '100 Newbury St', city: 'Boston', state: 'MA', zip: '02116' },
    tags: ['New'], source: 'google', assignee: 'Morgan L.',
    vehicleIds: ['v010'],
    estimateCount: 1, totalSpent: 5900, lifetimeValue: 5900,
    lastActivityAt: '2025-01-05T09:00:00Z', createdAt: '2025-01-05T09:00:00Z',
    status: 'active',
    notes: 'New customer. Just got the Supra. Classic taste — wants clean matte black.',
    activities: [
      { type: 'estimate', text: 'Estimate created — GR Supra full matte black', at: '2025-01-05T09:00:00Z' },
    ],
  },
  {
    id: 'c011', name: 'Layla Dixon',
    phone: '(404) 555-1055', email: 'layla.dixon@gmail.com',
    company: null, address: { street: '265 Peachtree Center Ave', city: 'Atlanta', state: 'GA', zip: '30303' },
    tags: ['Repeat'], source: 'yelp', assignee: 'Sam T.',
    vehicleIds: ['v011'],
    estimateCount: 2, totalSpent: 15600, lifetimeValue: 18000,
    lastActivityAt: '2024-10-05T09:00:00Z', createdAt: '2023-04-22T08:00:00Z',
    status: 'active',
    notes: 'Found us on Yelp. Changed wrap style entirely — previous orange, now candy red.',
    activities: [
      { type: 'job', text: 'Job completed — Challenger candy red + black accents', at: '2024-10-05T09:00:00Z' },
    ],
  },
  {
    id: 'c012', name: 'Marco Lima',
    phone: '(202) 555-1176', email: 'marco.lima@limadesign.co',
    company: 'Lima Design Co.', address: { street: '1600 K St NW', city: 'Washington', state: 'DC', zip: '20006' },
    tags: ['VIP', 'Repeat'], source: 'referral', assignee: 'Alex R.',
    vehicleIds: ['v012'],
    estimateCount: 2, totalSpent: 18400, lifetimeValue: 25000,
    lastActivityAt: '2024-11-22T10:00:00Z', createdAt: '2023-09-10T09:00:00Z',
    status: 'active',
    notes: 'Brand designer — very particular about color accuracy. Brings Pantone swatch.',
    activities: [
      { type: 'job', text: 'Job completed — Audi RS6 satin blue frost', at: '2024-11-22T10:00:00Z' },
      { type: 'note', text: 'Requested color-match documentation for insurance', at: '2024-11-23T09:00:00Z' },
    ],
  },
  {
    id: 'c013', name: 'Zoe Park',
    phone: '(949) 555-1297', email: 'zoe.park@icloud.com',
    company: null, address: { street: '520 Newport Center Dr', city: 'Newport Beach', state: 'CA', zip: '92660' },
    tags: ['VIP', 'Repeat'], source: 'instagram', assignee: 'Alex R.',
    vehicleIds: ['v013', 'v014'],
    estimateCount: 4, totalSpent: 24600, lifetimeValue: 35000,
    lastActivityAt: '2025-02-15T09:00:00Z', createdAt: '2022-12-01T09:00:00Z',
    status: 'active',
    notes: 'Two-car household. Loves dramatic wraps. Follow her IG for before/after feature.',
    activities: [
      { type: 'job', text: 'Job completed — Mustang GT500 matte blue + stripes', at: '2025-02-15T09:00:00Z' },
      { type: 'estimate', text: 'Estimate approved — Cayenne GTS trim accents', at: '2024-05-20T09:00:00Z' },
    ],
  },
  {
    id: 'c014', name: 'Brett Tanaka',
    phone: '(206) 555-1318', email: 'brett@tanakalogistics.com',
    company: 'Tanaka Logistics', address: { street: '1201 3rd Ave', city: 'Seattle', state: 'WA', zip: '98101' },
    tags: ['Fleet', 'Corporate', 'Wholesale'], source: 'dealer', assignee: 'Sam T.',
    vehicleIds: ['v015', 'v016'],
    estimateCount: 5, totalSpent: 41200, lifetimeValue: 80000,
    lastActivityAt: '2025-01-28T10:00:00Z', createdAt: '2024-04-01T09:00:00Z',
    status: 'active',
    notes: 'Fleet of 4+ TRX trucks. Wholesale pricing. Key account — do not lose.',
    activities: [
      { type: 'job', text: 'Fleet units 1 & 2 completed', at: '2025-01-28T10:00:00Z' },
      { type: 'estimate', text: 'Batch estimate for units 3 & 4 sent', at: '2025-02-01T09:00:00Z' },
    ],
  },
  {
    id: 'c015', name: 'Nia Foster',
    phone: '(415) 555-1439', email: 'nia.foster@gmail.com',
    company: null, address: { street: '600 Market St', city: 'San Francisco', state: 'CA', zip: '94105' },
    tags: ['New'], source: 'google', assignee: 'Jamie K.',
    vehicleIds: ['v017'],
    estimateCount: 1, totalSpent: 0, lifetimeValue: 3800,
    lastActivityAt: '2025-03-10T09:00:00Z', createdAt: '2025-03-10T09:00:00Z',
    status: 'active',
    notes: 'Brand new Rivian owner. Excited to protect and customize. In scheduling queue.',
    activities: [
      { type: 'estimate', text: 'Estimate created — Rivian R1T matte earth wrap', at: '2025-03-10T09:00:00Z' },
    ],
  },
  {
    id: 'c016', name: 'Kevin Shah',
    phone: '(858) 555-1560', email: 'kevin.shah@venturestudio.io',
    company: 'Venture Studio', address: { street: '4455 Executive Dr', city: 'San Diego', state: 'CA', zip: '92121' },
    tags: ['VIP', 'Repeat'], source: 'referral', assignee: 'Alex R.',
    vehicleIds: ['v018', 'v019'],
    estimateCount: 5, totalSpent: 38000, lifetimeValue: 55000,
    lastActivityAt: '2025-03-20T09:00:00Z', createdAt: '2021-03-01T09:00:00Z',
    status: 'active',
    notes: 'VC founder. Two Teslas. Loyal since 2021. Cybertruck is a new challenge.',
    activities: [
      { type: 'estimate', text: 'Estimate created — Cybertruck (research phase)', at: '2025-03-20T09:00:00Z' },
      { type: 'job', text: 'Model X rose gold wrap renewed', at: '2025-02-20T11:00:00Z' },
    ],
  },
  {
    id: 'c017', name: 'Destiny Monroe',
    phone: '(480) 555-1681', email: 'destiny@swiftdelivers.co',
    company: 'Swift Delivers', address: { street: '2025 N Central Ave', city: 'Phoenix', state: 'AZ', zip: '85004' },
    tags: ['Fleet', 'Corporate', 'Wholesale'], source: 'phone', assignee: 'Sam T.',
    vehicleIds: ['v020', 'v021'],
    estimateCount: 6, totalSpent: 58000, lifetimeValue: 120000,
    lastActivityAt: '2025-01-05T08:00:00Z', createdAt: '2022-06-01T09:00:00Z',
    status: 'active',
    notes: 'Largest fleet account. 6 Sprinters branded. 4 more vans expected mid-year.',
    activities: [
      { type: 'job', text: 'Sprinter fleet batch 2 completed (2 units)', at: '2025-01-05T08:00:00Z' },
      { type: 'note', text: 'Q2 expansion confirmed — 4 Ford Transits incoming', at: '2025-02-15T09:00:00Z' },
    ],
  },
  {
    id: 'c018', name: 'Eli Torres',
    phone: '(503) 555-1702', email: 'eli.torres@gmail.com',
    company: null, address: { street: '1234 NW Thurman St', city: 'Portland', state: 'OR', zip: '97209' },
    tags: [], source: 'yelp', assignee: 'Morgan L.',
    vehicleIds: ['v022'],
    estimateCount: 1, totalSpent: 1800, lifetimeValue: 1800,
    lastActivityAt: '2024-11-10T09:00:00Z', createdAt: '2024-09-01T09:00:00Z',
    status: 'active',
    notes: 'Modest budget, partial wrap only. Civic enthusiast community — could generate referrals.',
    activities: [
      { type: 'job', text: 'Partial wrap completed — carbon fiber accents', at: '2024-11-10T09:00:00Z' },
    ],
  },
  {
    id: 'c019', name: 'Simone Carter',
    phone: '(702) 555-1823', email: 'simone@cartergroup.com',
    company: 'Carter Group', address: { street: '3600 S Las Vegas Blvd', city: 'Las Vegas', state: 'NV', zip: '89109' },
    tags: ['VIP', 'Corporate', 'Repeat'], source: 'website', assignee: 'Alex R.',
    vehicleIds: ['v023'],
    estimateCount: 2, totalSpent: 21000, lifetimeValue: 28000,
    lastActivityAt: '2024-12-15T09:00:00Z', createdAt: '2023-07-01T09:00:00Z',
    status: 'active',
    notes: 'Real estate mogul. All-black everything. No chrome. Extremely precise expectations.',
    activities: [
      { type: 'job', text: 'Escalade full blackout completed', at: '2024-12-15T09:00:00Z' },
      { type: 'payment', text: 'Full payment received — $11,200', at: '2024-12-15T14:00:00Z' },
    ],
  },
  {
    id: 'c020', name: 'Tyler Kim',
    phone: '(253) 555-1944', email: 'tyler.kim@gmail.com',
    company: null, address: { street: '201 St Helens Ave', city: 'Tacoma', state: 'WA', zip: '98402' },
    tags: ['Repeat'], source: 'instagram', assignee: 'Morgan L.',
    vehicleIds: ['v024'],
    estimateCount: 2, totalSpent: 8200, lifetimeValue: 10000,
    lastActivityAt: '2024-08-20T09:00:00Z', createdAt: '2023-01-15T09:00:00Z',
    status: 'active',
    notes: 'Rally / autocross driver. Needs track-certified film. Posts build threads online.',
    activities: [
      { type: 'job', text: 'Job completed — WRX STI matte rally red', at: '2024-08-20T09:00:00Z' },
    ],
  },
];

export const SEED_ESTIMATES = [
  // active
  {
    id: 'EST-3799',
    type: 'estimate',
    title: 'Window Tint - Two (2) Doors and 1 more',
    services: ['Window Tint', 'Door Tint'],
    columnId: 'active',
    vehicle: { year: 2026, make: 'Land Rover', model: 'Range Rover Sport', vin: 'SAL1L9E90TA634357', type: 'SUV' },
    customer: { name: 'Eric Brooks', phone: '(818) 970-6116', email: 'eric.brooks@example.com' },
    tags: ['VIP'],
    total: 7156.01,
    paid: 207.00,
    paymentStatus: 'partial',
    daysInColumn: 1,
    scheduledDate: null,
    assignee: 'Tavo R.',
    priority: 'high',
    note: 'Customer wants matte ceramic finish',
    createdAt: iso(-1),
  },
  {
    id: 'EST-3801',
    type: 'estimate',
    title: 'Chrome Delete - Trim and Badges',
    services: ['Chrome Delete'],
    columnId: 'active',
    vehicle: { year: 2024, make: 'BMW', model: 'M4 Competition', vin: 'WBS83AC03RFR12398', type: 'Coupe' },
    customer: { name: 'Priya Nair', phone: '(310) 555-2088', email: 'priya@example.com' },
    tags: ['PPF', 'Repeat Client'],
    total: 2850.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 0,
    scheduledDate: null,
    assignee: null,
    priority: 'normal',
    note: '',
    createdAt: iso(0),
  },
  {
    id: 'EST-3812',
    type: 'estimate',
    title: 'Full Vehicle PPF - XPEL Stealth',
    services: ['Full Vehicle PPF', 'XPEL Stealth'],
    columnId: 'active',
    vehicle: { year: 2023, make: 'Porsche', model: '911 Turbo S', vin: 'WP0AD2A99PS267801', type: 'Coupe' },
    customer: { name: 'Marcus Bell', phone: '(424) 555-0143', email: 'm.bell@example.com' },
    tags: ['VIP', 'PPF', 'Rush'],
    total: 17850.00,
    paid: 5000.00,
    paymentStatus: 'partial',
    daysInColumn: 2,
    scheduledDate: null,
    assignee: 'Chris M.',
    priority: 'urgent',
    note: 'Rush for Pebble Beach show',
    createdAt: iso(-2),
  },

  // deposit
  {
    id: 'EST-3755',
    type: 'estimate',
    title: 'Color Change - Gloss Black Full Wrap',
    services: ['Full Wrap', 'Color Change – Gloss Black'],
    columnId: 'deposit',
    vehicle: { year: 2023, make: 'Tesla', model: 'Model S Plaid', vin: '5YJSA1E68PF123456', type: 'Sedan' },
    customer: { name: 'Jordan Cole', phone: '(213) 555-9812', email: 'jordan.cole@example.com' },
    tags: ['Rush'],
    total: 6200.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 4,
    scheduledDate: null,
    assignee: 'Maria L.',
    priority: 'high',
    note: 'Awaiting 50% deposit',
    createdAt: iso(-4),
  },
  {
    id: 'EST-3760',
    type: 'estimate',
    title: 'Hood PPF + Ceramic Coating',
    services: ['Hood PPF', 'Ceramic Coating'],
    columnId: 'deposit',
    vehicle: { year: 2025, make: 'Audi', model: 'RS6 Avant', vin: 'WUAWFAFX0P0900123', type: 'Wagon' },
    customer: { name: 'Remi Santos', phone: '(714) 555-4422', email: 'remi@example.com' },
    tags: ['PPF'],
    total: 3400.00,
    paid: 500.00,
    paymentStatus: 'partial',
    daysInColumn: 3,
    scheduledDate: null,
    assignee: 'Daniel V.',
    priority: 'normal',
    note: '',
    createdAt: iso(-3),
  },
  {
    id: 'EST-3768',
    type: 'estimate',
    title: 'Partial Wrap - Roof and Mirrors',
    services: ['Partial Wrap', 'Roof Wrap'],
    columnId: 'deposit',
    vehicle: { year: 2022, make: 'Mercedes', model: 'G-Wagon 63', vin: 'W1NWF8HBXNX789456', type: 'SUV' },
    customer: { name: 'Carla Reyes', phone: '(818) 555-3399', email: 'carla.reyes@example.com' },
    tags: ['VIP', 'Repeat Client'],
    total: 4450.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 9,
    scheduledDate: null,
    assignee: null,
    priority: 'normal',
    note: 'Following up Wednesday',
    createdAt: iso(-9),
  },

  // followup
  {
    id: 'EST-3702',
    type: 'estimate',
    title: 'Full Wrap - Satin White',
    services: ['Full Wrap – Satin White'],
    columnId: 'followup',
    vehicle: { year: 2021, make: 'Ford', model: 'F-150 Raptor', vin: '1FTFW1RG2MFA12345', type: 'Truck' },
    customer: { name: 'Devon Walsh', phone: '(562) 555-7712', email: 'devon@example.com' },
    tags: ['Cold'],
    total: 8900.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 14,
    scheduledDate: null,
    assignee: 'Tavo R.',
    priority: 'normal',
    note: 'Customer went quiet – try again Friday',
    createdAt: iso(-14),
  },
  {
    id: 'EST-3689',
    type: 'estimate',
    title: 'Window Tint - Full Vehicle Ceramic',
    services: ['Window Tint', 'Ceramic Tint'],
    columnId: 'followup',
    vehicle: { year: 2020, make: 'Jeep', model: 'Wrangler Rubicon', vin: '1C4HJXFN5LW123789', type: 'SUV' },
    customer: { name: 'Aisha Owens', phone: '(949) 555-2211', email: 'aisha@example.com' },
    tags: ['Referral'],
    total: 1250.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 7,
    scheduledDate: null,
    assignee: null,
    priority: 'normal',
    note: '',
    createdAt: iso(-7),
  },
  {
    id: 'EST-3717',
    type: 'estimate',
    title: 'Fleet Wrap - 3 Ford Transits',
    services: ['Fleet Wrap', 'Branding'],
    columnId: 'followup',
    vehicle: { year: 2024, make: 'Ford', model: 'Transit 350', vin: '1FTBR1Y88PKA34567', type: 'Van' },
    customer: { name: 'Finn O\'Brien', phone: '(323) 555-6611', email: 'finn.obrien@example.com' },
    tags: ['Fleet', 'Cold'],
    total: 13400.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 21,
    scheduledDate: null,
    assignee: 'Maria L.',
    priority: 'high',
    note: 'Pending approval from accounting',
    createdAt: iso(-21),
  },

  // scheduled
  {
    id: 'EST-3820',
    type: 'estimate',
    title: 'Roof Wrap - Gloss Black',
    services: ['Roof Wrap'],
    columnId: 'scheduled',
    vehicle: { year: 2023, make: 'Chevy', model: 'Silverado 1500', vin: '1GCUYGED5PZ123456', type: 'Truck' },
    customer: { name: 'Kyle Huang', phone: '(626) 555-8822', email: 'kyle@example.com' },
    tags: ['Blackout'],
    total: 1850.00,
    paid: 925.00,
    paymentStatus: 'partial',
    daysInColumn: 2,
    scheduledDate: iso(3),
    assignee: 'Tavo R.',
    priority: 'normal',
    note: 'Scheduled for Thursday AM',
    createdAt: iso(-2),
  },
  {
    id: 'EST-3822',
    type: 'estimate',
    title: 'Full Vehicle PPF + Window Tint',
    services: ['Full Vehicle PPF', 'Window Tint'],
    columnId: 'scheduled',
    vehicle: { year: 2025, make: 'Rivian', model: 'R1T', vin: '7FCTGAAL2PN012345', type: 'Truck' },
    customer: { name: 'Layla Dixon', phone: '(805) 555-1144', email: 'layla.dixon@example.com' },
    tags: ['PPF', 'VIP'],
    total: 12800.00,
    paid: 6400.00,
    paymentStatus: 'partial',
    daysInColumn: 1,
    scheduledDate: iso(5),
    assignee: 'Chris M.',
    priority: 'high',
    note: '',
    createdAt: iso(-1),
  },
  {
    id: 'EST-3825',
    type: 'estimate',
    title: 'Chrome Delete + Badge Blackout',
    services: ['Chrome Delete', 'Badge Blackout'],
    columnId: 'scheduled',
    vehicle: { year: 2024, make: 'Dodge', model: 'Challenger Hellcat', vin: '2C3CDZFJ8RH123456', type: 'Coupe' },
    customer: { name: 'Marco Lima', phone: '(951) 555-6633', email: 'marco@example.com' },
    tags: ['Blackout', 'Repeat Client'],
    total: 1650.00,
    paid: 825.00,
    paymentStatus: 'partial',
    daysInColumn: 0,
    scheduledDate: iso(2),
    assignee: 'Daniel V.',
    priority: 'normal',
    note: '',
    createdAt: iso(0),
  },

  // inprog
  {
    id: 'EST-3700',
    type: 'estimate',
    title: 'Full Vehicle PPF - XPEL Stealth',
    services: ['Full Vehicle PPF', 'XPEL Stealth'],
    columnId: 'inprog',
    vehicle: { year: 2024, make: 'Lamborghini', model: 'Urus Performante', vin: 'ZPBUA1ZL6RLA12345', type: 'SUV' },
    customer: { name: 'Tina Marsh', phone: '(310) 555-9090', email: 'tina@example.com' },
    tags: ['VIP', 'PPF', 'Rush'],
    total: 18400.00,
    paid: 9200.00,
    paymentStatus: 'partial',
    daysInColumn: 3,
    scheduledDate: null,
    assignee: 'Chris M.',
    priority: 'urgent',
    note: 'Day 3 of 5 – on track',
    createdAt: iso(-3),
  },
  {
    id: 'EST-3695',
    type: 'estimate',
    title: 'Partial Wrap - Hood and Roof',
    services: ['Partial Wrap', 'Hood PPF'],
    columnId: 'inprog',
    vehicle: { year: 2024, make: 'Toyota', model: 'Tundra TRD Pro', vin: '5TFWC5DB9RX123456', type: 'Truck' },
    customer: { name: 'Chris Benitez', phone: '(760) 555-3311', email: 'chris.b@example.com' },
    tags: [],
    total: 3950.00,
    paid: 1975.00,
    paymentStatus: 'partial',
    daysInColumn: 1,
    scheduledDate: null,
    assignee: 'Tavo R.',
    priority: 'normal',
    note: '',
    createdAt: iso(-1),
  },

  // invoice
  {
    id: 'INV-2204',
    type: 'invoice',
    title: 'Full Wrap - Satin Metallic Blue',
    services: ['Full Wrap', 'Color Change'],
    columnId: 'invoice',
    vehicle: { year: 2023, make: 'Cadillac', model: 'Escalade Sport', vin: '1GYS4NKL8PR123456', type: 'SUV' },
    customer: { name: 'Alicia Green', phone: '(818) 555-7744', email: 'alicia.green@example.com' },
    tags: ['VIP'],
    total: 9850.00,
    paid: 5000.00,
    paymentStatus: 'partial',
    daysInColumn: 2,
    scheduledDate: null,
    assignee: 'Maria L.',
    priority: 'high',
    note: 'Invoice sent – awaiting final payment',
    createdAt: iso(-2),
  },
  {
    id: 'INV-2198',
    type: 'invoice',
    title: 'Window Tint - Full Vehicle',
    services: ['Window Tint'],
    columnId: 'invoice',
    vehicle: { year: 2024, make: 'Honda', model: 'Ridgeline Black Ed.', vin: '5FPYK3F85RB012345', type: 'Truck' },
    customer: { name: 'Hiro Tanaka', phone: '(714) 555-4477', email: 'hiro@example.com' },
    tags: ['Referral'],
    total: 1320.00,
    paid: 1320.00,
    paymentStatus: 'paid',
    daysInColumn: 1,
    scheduledDate: null,
    assignee: 'Daniel V.',
    priority: 'normal',
    note: '',
    createdAt: iso(-1),
  },

  // dead (work done, not paid)
  {
    id: 'INV-2176',
    type: 'invoice',
    title: 'Partial Wrap + Chrome Delete',
    services: ['Partial Wrap', 'Chrome Delete'],
    columnId: 'dead',
    vehicle: { year: 2022, make: 'Kia', model: 'Telluride SX', vin: '5XYP5DHC5NG123456', type: 'SUV' },
    customer: { name: 'Reina Alvarez', phone: '(562) 555-9988', email: 'reina@example.com' },
    tags: ['Warranty'],
    total: 2450.00,
    paid: 1000.00,
    paymentStatus: 'partial',
    daysInColumn: 12,
    scheduledDate: null,
    assignee: 'Maria L.',
    priority: 'high',
    note: 'Customer unresponsive to final invoice',
    createdAt: iso(-12),
  },
  {
    id: 'INV-2163',
    type: 'invoice',
    title: 'Ceramic Coating - Full Exterior',
    services: ['Ceramic Coating'],
    columnId: 'dead',
    vehicle: { year: 2021, make: 'BMW', model: 'X5 M50i', vin: '5UXJU2C00M9A12345', type: 'SUV' },
    customer: { name: 'Nathan Price', phone: '(213) 555-2266', email: 'n.price@example.com' },
    tags: ['Cold'],
    total: 1900.00,
    paid: 0,
    paymentStatus: 'unpaid',
    daysInColumn: 18,
    scheduledDate: null,
    assignee: 'Chris M.',
    priority: 'urgent',
    note: 'Second invoice sent',
    createdAt: iso(-18),
  },

  // complete
  {
    id: 'INV-2150',
    type: 'invoice',
    title: 'Full Vehicle PPF - XPEL Ultimate',
    services: ['Full Vehicle PPF'],
    columnId: 'complete',
    vehicle: { year: 2024, make: 'Tesla', model: 'Model X Plaid', vin: '7SAXCBE60RF123456', type: 'SUV' },
    customer: { name: 'Sienna Park', phone: '(310) 555-4411', email: 'sienna@example.com' },
    tags: ['PPF', 'Repeat Client'],
    total: 15200.00,
    paid: 15200.00,
    paymentStatus: 'paid',
    daysInColumn: 3,
    scheduledDate: null,
    assignee: 'Chris M.',
    priority: 'normal',
    note: '',
    createdAt: iso(-3),
  },
  {
    id: 'INV-2145',
    type: 'invoice',
    title: 'Full Wrap - Satin White',
    services: ['Full Wrap – Satin White'],
    columnId: 'complete',
    vehicle: { year: 2023, make: 'Ford', model: 'F-150 Raptor R', vin: '1FTFW1RJ0PFA67890', type: 'Truck' },
    customer: { name: 'Trevor Klein', phone: '(818) 555-5533', email: 'trevor@example.com' },
    tags: ['VIP'],
    total: 8650.00,
    paid: 8650.00,
    paymentStatus: 'paid',
    daysInColumn: 5,
    scheduledDate: null,
    assignee: 'Tavo R.',
    priority: 'normal',
    note: '',
    createdAt: iso(-5),
  },
  {
    id: 'INV-2142',
    type: 'invoice',
    title: 'Window Tint + Chrome Delete',
    services: ['Window Tint', 'Chrome Delete'],
    columnId: 'complete',
    vehicle: { year: 2024, make: 'Audi', model: 'RS6 Performance', vin: 'WUAPCBFX7R0001234', type: 'Wagon' },
    customer: { name: 'Jasmine Wu', phone: '(949) 555-1199', email: 'jasmine@example.com' },
    tags: ['Blackout'],
    total: 2150.00,
    paid: 2150.00,
    paymentStatus: 'paid',
    daysInColumn: 8,
    scheduledDate: null,
    assignee: 'Daniel V.',
    priority: 'normal',
    note: '',
    createdAt: iso(-8),
  },
];

export const SEED_LEADS = [
  // ─── NEW (5) ──────────────────────────────────────────────────────────────
  {
    id: 'lead-001',
    name: 'Marcus Chen',
    phone: '(714) 882-3401',
    email: 'marcus.chen@outlook.com',
    vehicle: { year: 2024, make: 'Lamborghini', model: 'Urus' },
    serviceInterest: 'Full Vehicle PPF',
    budget: 14000,
    source: 'google',
    status: 'new',
    priority: 'hot',
    assignee: 'Maria L.',
    tags: ['VIP', 'Rush'],
    notes: 'Wants XPEL Ultimate Plus — needs car ready for Monaco trip.',
    followUpDate: daysAhead(2),
    createdAt: daysAgo(1, 9),
    lastContactedAt: null,
    activities: [
      { type: 'created', text: 'Lead created from Google Ads form', at: daysAgo(1, 9) },
    ],
  },
  {
    id: 'lead-002',
    name: 'Jessica Ramirez',
    phone: '(818) 970-6116',
    email: 'jess.ramirez@gmail.com',
    vehicle: { year: 2023, make: 'Tesla', model: 'Model 3' },
    serviceInterest: 'Color Change – Satin Black',
    budget: 4200,
    source: 'instagram',
    status: 'new',
    priority: 'warm',
    assignee: null,
    tags: [],
    notes: 'Saw us on IG reel. Prefers satin black.',
    followUpDate: null,
    createdAt: daysAgo(0, 14),
    lastContactedAt: null,
    activities: [
      { type: 'created', text: 'Lead created via Instagram DM', at: daysAgo(0, 14) },
    ],
  },
  {
    id: 'lead-003',
    name: 'Derek Patel',
    phone: '(310) 441-2265',
    email: 'dpatel.films@icloud.com',
    vehicle: { year: 2024, make: 'Porsche', model: 'Taycan' },
    serviceInterest: 'XPEL Stealth Full Front',
    budget: 3800,
    source: 'yelp',
    status: 'new',
    priority: 'warm',
    assignee: 'Tavo R.',
    tags: ['Referral'],
    notes: 'Friend referred — wants a quote for Stealth PPF.',
    followUpDate: daysAhead(3),
    createdAt: daysAgo(2, 11),
    lastContactedAt: null,
    activities: [
      { type: 'created', text: 'Lead created from Yelp inquiry', at: daysAgo(2, 11) },
    ],
  },
  {
    id: 'lead-004',
    name: 'Sandra Okafor',
    phone: '(213) 776-4420',
    email: 'sandra.o@protonmail.com',
    vehicle: { year: 2022, make: 'Range Rover', model: 'Sport' },
    serviceInterest: 'Window Tint 35%',
    budget: 650,
    source: 'website',
    status: 'new',
    priority: 'cold',
    assignee: null,
    tags: [],
    notes: '',
    followUpDate: null,
    createdAt: daysAgo(3, 16),
    lastContactedAt: null,
    activities: [
      { type: 'created', text: 'Lead submitted via website form', at: daysAgo(3, 16) },
    ],
  },
  {
    id: 'lead-005',
    name: 'Brian Halvorsen',
    phone: '(949) 223-8870',
    email: 'bhalvorsen@vistacorp.com',
    vehicle: { year: 2024, make: 'Ford', model: 'F-150 Raptor' },
    serviceInterest: 'Hood + Fenders PPF',
    budget: 2400,
    source: 'facebook',
    status: 'new',
    priority: 'hot',
    assignee: 'Daniel V.',
    tags: ['Rush'],
    notes: 'Brand new truck. Wants it done ASAP before a trip.',
    followUpDate: daysAhead(1),
    createdAt: daysAgo(1, 13),
    lastContactedAt: null,
    activities: [
      { type: 'created', text: 'Lead created from Facebook Ads', at: daysAgo(1, 13) },
    ],
  },

  // ─── CONTACTED (4) ────────────────────────────────────────────────────────
  {
    id: 'lead-006',
    name: 'Olivia Bennett',
    phone: '(626) 335-9812',
    email: 'olivia.b@bennettfirm.com',
    vehicle: { year: 2024, make: 'BMW', model: 'M5' },
    serviceInterest: 'Full Vehicle PPF',
    budget: 9200,
    source: 'referral',
    status: 'contacted',
    priority: 'hot',
    assignee: 'Maria L.',
    tags: ['VIP', 'Referral'],
    notes: 'Attorney — values premium product. Called and discussed XPEL Ultimate.',
    followUpDate: daysAhead(2),
    createdAt: daysAgo(5, 10),
    lastContactedAt: daysAgo(1, 14),
    activities: [
      { type: 'created', text: 'Lead created via referral from Alex M.', at: daysAgo(5, 10) },
      { type: 'call', text: 'Initial call — 12 min — discussed package options', at: daysAgo(3, 11) },
      { type: 'email', text: 'Sent PPF brochure and pricing sheet', at: daysAgo(2, 15) },
      { type: 'note', text: 'Very engaged — schedule walk-in.', at: daysAgo(1, 14) },
    ],
  },
  {
    id: 'lead-007',
    name: 'Tyler Nakamura',
    phone: '(408) 667-1198',
    email: 'tnakamura@pivotlab.co',
    vehicle: { year: 2023, make: 'Rivian', model: 'R1T' },
    serviceInterest: 'Color Change – Satin Black',
    budget: 6500,
    source: 'google',
    status: 'contacted',
    priority: 'warm',
    assignee: 'Chris M.',
    tags: [],
    notes: 'Tech exec — wants stealth look for daily driver.',
    followUpDate: daysAhead(4),
    createdAt: daysAgo(7, 10),
    lastContactedAt: daysAgo(2, 10),
    activities: [
      { type: 'created', text: 'Lead created from Google Ads', at: daysAgo(7, 10) },
      { type: 'call', text: 'Phone consultation — 8 min', at: daysAgo(4, 14) },
      { type: 'email', text: 'Sent material samples info', at: daysAgo(2, 10) },
    ],
  },
  {
    id: 'lead-008',
    name: 'Amanda Wu',
    phone: '(415) 882-0099',
    email: 'amanda.wu@stride.io',
    vehicle: { year: 2024, make: 'Audi', model: 'Q8' },
    serviceInterest: 'Window Tint 35%',
    budget: 850,
    source: 'website',
    status: 'contacted',
    priority: 'warm',
    assignee: 'Tavo R.',
    tags: [],
    notes: 'Needs ceramic tint — has kids.',
    followUpDate: daysAhead(1),
    createdAt: daysAgo(4, 12),
    lastContactedAt: daysAgo(1, 11),
    activities: [
      { type: 'created', text: 'Lead from website form', at: daysAgo(4, 12) },
      { type: 'email', text: 'Initial reply — requested VIN', at: daysAgo(3, 10) },
      { type: 'call', text: 'Left voicemail', at: daysAgo(1, 11) },
    ],
  },
  {
    id: 'lead-009',
    name: 'Kenji Morales',
    phone: '(562) 441-7720',
    email: 'kmorales@fleetlogix.net',
    vehicle: { year: 2023, make: 'Chevy', model: 'Suburban' },
    serviceInterest: 'Full Wrap – Matte White',
    budget: 5500,
    source: 'zapier',
    status: 'contacted',
    priority: 'cold',
    assignee: 'Daniel V.',
    tags: ['Fleet'],
    notes: 'Has 4 Suburbans — will do one first, then rest if happy.',
    followUpDate: daysAhead(7),
    createdAt: daysAgo(10, 9),
    lastContactedAt: daysAgo(5, 13),
    activities: [
      { type: 'created', text: 'Pushed from Zapier integration', at: daysAgo(10, 9) },
      { type: 'call', text: 'Intro call — 15 min', at: daysAgo(6, 10) },
      { type: 'note', text: 'Send fleet pricing PDF', at: daysAgo(5, 13) },
    ],
  },

  // ─── QUOTED (4) ───────────────────────────────────────────────────────────
  {
    id: 'lead-010',
    name: 'Victoria Park',
    phone: '(818) 224-5566',
    email: 'vpark@vparchitects.com',
    vehicle: { year: 2024, make: 'Mercedes', model: 'AMG GLE63' },
    serviceInterest: 'Full Vehicle PPF',
    budget: 11500,
    source: 'referral',
    status: 'quoted',
    priority: 'hot',
    assignee: 'Maria L.',
    tags: ['VIP', 'Referral'],
    notes: 'Sent formal quote — waiting on decision. Very likely to convert.',
    followUpDate: daysAhead(2),
    createdAt: daysAgo(12, 11),
    lastContactedAt: daysAgo(2, 15),
    activities: [
      { type: 'created', text: 'Lead from architect referral', at: daysAgo(12, 11) },
      { type: 'call', text: 'Consultation call — 20 min', at: daysAgo(8, 14) },
      { type: 'status_change', text: 'Moved from Contacted → Quoted', at: daysAgo(3, 10) },
      { type: 'email', text: 'Sent full quote PDF — $11,500', at: daysAgo(3, 10) },
      { type: 'note', text: 'Following up in 48 hours', at: daysAgo(2, 15) },
    ],
  },
  {
    id: 'lead-011',
    name: 'Roger Stanfield',
    phone: '(310) 990-1108',
    email: 'rstanfield@stanfieldrealty.com',
    vehicle: { year: 2022, make: 'Cadillac', model: 'Escalade' },
    serviceInterest: 'Chrome Delete',
    budget: 2800,
    source: 'phone',
    status: 'quoted',
    priority: 'warm',
    assignee: 'Chris M.',
    tags: ['Repeat Client'],
    notes: 'Returning customer — did wrap in 2022.',
    followUpDate: daysAhead(5),
    createdAt: daysAgo(8, 10),
    lastContactedAt: daysAgo(4, 11),
    activities: [
      { type: 'created', text: 'Walk-in at the shop', at: daysAgo(8, 10) },
      { type: 'status_change', text: 'Moved to Quoted', at: daysAgo(4, 11) },
      { type: 'email', text: 'Quote sent: $2,800', at: daysAgo(4, 11) },
    ],
  },
  {
    id: 'lead-012',
    name: 'Priya Desai',
    phone: '(714) 220-3319',
    email: 'priya.desai@alliedmed.com',
    vehicle: { year: 2024, make: 'Genesis', model: 'GV80' },
    serviceInterest: 'Ceramic Coating + Tint Combo',
    budget: 1900,
    source: 'yelp',
    status: 'quoted',
    priority: 'warm',
    assignee: 'Tavo R.',
    tags: [],
    notes: 'Quoted combo package — comparing with a competitor.',
    followUpDate: daysAhead(3),
    createdAt: daysAgo(9, 13),
    lastContactedAt: daysAgo(3, 14),
    activities: [
      { type: 'created', text: 'Lead from Yelp', at: daysAgo(9, 13) },
      { type: 'call', text: 'Discussed options — 10 min', at: daysAgo(5, 11) },
      { type: 'email', text: 'Sent quote: $1,900', at: daysAgo(3, 14) },
    ],
  },
  {
    id: 'lead-013',
    name: 'Lucas Tremblay',
    phone: '(949) 771-4040',
    email: 'lucas.tremblay@northstar.ca',
    vehicle: { year: 2024, make: 'Chevy', model: 'Corvette' },
    serviceInterest: 'XPEL Stealth Full Front',
    budget: 3500,
    source: 'instagram',
    status: 'quoted',
    priority: 'hot',
    assignee: 'Maria L.',
    tags: ['Rush'],
    notes: 'Needs it done before a track day on the 20th.',
    followUpDate: daysAhead(1),
    createdAt: daysAgo(6, 10),
    lastContactedAt: daysAgo(1, 16),
    activities: [
      { type: 'created', text: 'Lead from Instagram inquiry', at: daysAgo(6, 10) },
      { type: 'call', text: 'Initial call — 5 min', at: daysAgo(4, 12) },
      { type: 'email', text: 'Formal quote sent', at: daysAgo(1, 16) },
    ],
  },

  // ─── SCHEDULED (3) ────────────────────────────────────────────────────────
  {
    id: 'lead-014',
    name: 'Natalie Brooks',
    phone: '(626) 551-7710',
    email: 'natalie@brooksco.com',
    vehicle: { year: 2023, make: 'Jeep', model: 'Wrangler' },
    serviceInterest: 'Partial Wrap',
    budget: 2200,
    source: 'facebook',
    status: 'scheduled',
    priority: 'warm',
    assignee: 'Daniel V.',
    tags: [],
    notes: 'Scheduled for next Tuesday drop-off.',
    followUpDate: daysAhead(6),
    createdAt: daysAgo(14, 10),
    lastContactedAt: daysAgo(2, 11),
    activities: [
      { type: 'created', text: 'FB Ads lead', at: daysAgo(14, 10) },
      { type: 'call', text: 'Consultation', at: daysAgo(9, 14) },
      { type: 'status_change', text: 'Moved to Scheduled', at: daysAgo(2, 11) },
    ],
  },
  {
    id: 'lead-015',
    name: 'Edwin Reyes',
    phone: '(213) 662-8089',
    email: 'edwin.reyes@lapm.gov',
    vehicle: { year: 2023, make: 'Dodge', model: 'Durango SRT' },
    serviceInterest: 'Color Change – Gloss Black',
    budget: 6200,
    source: 'google',
    status: 'scheduled',
    priority: 'hot',
    assignee: 'Chris M.',
    tags: ['VIP'],
    notes: 'Booked in for Thursday — full gloss black wrap.',
    followUpDate: daysAhead(3),
    createdAt: daysAgo(18, 11),
    lastContactedAt: daysAgo(3, 10),
    activities: [
      { type: 'created', text: 'Google Ads lead', at: daysAgo(18, 11) },
      { type: 'call', text: 'Initial consult — 15 min', at: daysAgo(14, 13) },
      { type: 'email', text: 'Quote accepted', at: daysAgo(6, 10) },
      { type: 'status_change', text: 'Moved to Scheduled', at: daysAgo(3, 10) },
    ],
  },
  {
    id: 'lead-016',
    name: 'Holly Vang',
    phone: '(408) 881-2017',
    email: 'holly.vang@vangdesign.com',
    vehicle: { year: 2022, make: 'Kia', model: 'Telluride' },
    serviceInterest: 'Window Tint 35%',
    budget: 720,
    source: 'website',
    status: 'scheduled',
    priority: 'cold',
    assignee: 'Tavo R.',
    tags: [],
    notes: 'Drop-off scheduled Friday morning.',
    followUpDate: daysAhead(4),
    createdAt: daysAgo(11, 12),
    lastContactedAt: daysAgo(4, 13),
    activities: [
      { type: 'created', text: 'Website form submission', at: daysAgo(11, 12) },
      { type: 'email', text: 'Quote sent', at: daysAgo(7, 10) },
      { type: 'status_change', text: 'Moved to Scheduled', at: daysAgo(4, 13) },
    ],
  },

  // ─── WON (4) ──────────────────────────────────────────────────────────────
  {
    id: 'lead-017',
    name: 'Harrison Leone',
    phone: '(818) 447-2200',
    email: 'hleone@leoneauto.com',
    vehicle: { year: 2024, make: 'Ferrari', model: 'Roma' },
    serviceInterest: 'Full Vehicle PPF',
    budget: 17500,
    source: 'referral',
    status: 'won',
    priority: 'hot',
    assignee: 'Maria L.',
    tags: ['VIP', 'Referral'],
    notes: 'Closed — XPEL Ultimate Plus, full car. Paid deposit.',
    followUpDate: null,
    createdAt: daysAgo(25, 11),
    lastContactedAt: daysAgo(2, 10),
    activities: [
      { type: 'created', text: 'Referral from luxury dealership', at: daysAgo(25, 11) },
      { type: 'call', text: 'Consultation — 30 min', at: daysAgo(20, 13) },
      { type: 'email', text: 'Quote sent: $17,500', at: daysAgo(15, 10) },
      { type: 'status_change', text: 'Quote accepted — moved to Won', at: daysAgo(2, 10) },
    ],
  },
  {
    id: 'lead-018',
    name: 'Monica Ashford',
    phone: '(714) 993-6540',
    email: 'monica.a@ashfordpr.com',
    vehicle: { year: 2024, make: 'BMW', model: 'X5M' },
    serviceInterest: 'Full Vehicle PPF',
    budget: 9800,
    source: 'google',
    status: 'won',
    priority: 'warm',
    assignee: 'Chris M.',
    tags: ['VIP'],
    notes: 'Deposit paid. Scheduled for install next week.',
    followUpDate: null,
    createdAt: daysAgo(30, 10),
    lastContactedAt: daysAgo(5, 12),
    activities: [
      { type: 'created', text: 'Google Ads lead', at: daysAgo(30, 10) },
      { type: 'call', text: 'Consult — 18 min', at: daysAgo(22, 13) },
      { type: 'email', text: 'Quote accepted', at: daysAgo(5, 12) },
      { type: 'status_change', text: 'Moved to Won', at: daysAgo(5, 12) },
    ],
  },
  {
    id: 'lead-019',
    name: 'Sean Kowalski',
    phone: '(562) 117-3321',
    email: 'sean.k@kowfit.com',
    vehicle: { year: 2023, make: 'Ram', model: '1500 TRX' },
    serviceInterest: 'Hood + Fenders PPF',
    budget: 4400,
    source: 'facebook',
    status: 'won',
    priority: 'warm',
    assignee: 'Daniel V.',
    tags: ['Repeat Client'],
    notes: 'Second vehicle for this customer. Deposit in.',
    followUpDate: null,
    createdAt: daysAgo(22, 12),
    lastContactedAt: daysAgo(4, 11),
    activities: [
      { type: 'created', text: 'FB Ads lead', at: daysAgo(22, 12) },
      { type: 'email', text: 'Quote sent', at: daysAgo(12, 10) },
      { type: 'status_change', text: 'Won — deposit received', at: daysAgo(4, 11) },
    ],
  },
  {
    id: 'lead-020',
    name: 'Isabel Fournier',
    phone: '(949) 554-8877',
    email: 'ifournier@seapointgroup.com',
    vehicle: { year: 2024, make: 'Toyota', model: 'Tundra TRD' },
    serviceInterest: 'Full Wrap – Matte White',
    budget: 5800,
    source: 'yelp',
    status: 'won',
    priority: 'warm',
    assignee: 'Tavo R.',
    tags: [],
    notes: 'Confirmed for next week install.',
    followUpDate: null,
    createdAt: daysAgo(28, 11),
    lastContactedAt: daysAgo(6, 10),
    activities: [
      { type: 'created', text: 'Yelp inquiry', at: daysAgo(28, 11) },
      { type: 'call', text: 'Consult', at: daysAgo(18, 13) },
      { type: 'status_change', text: 'Moved to Won', at: daysAgo(6, 10) },
    ],
  },

  // ─── LOST (4) ─────────────────────────────────────────────────────────────
  {
    id: 'lead-021',
    name: 'Craig Iverson',
    phone: '(310) 221-4455',
    email: 'craig.iverson@ivtech.io',
    vehicle: { year: 2022, make: 'Honda', model: 'Ridgeline' },
    serviceInterest: 'Partial Wrap',
    budget: 1500,
    source: 'website',
    status: 'lost',
    priority: 'cold',
    assignee: 'Tavo R.',
    tags: [],
    notes: 'Went with a competitor — price.',
    followUpDate: null,
    createdAt: daysAgo(40, 10),
    lastContactedAt: daysAgo(15, 11),
    activities: [
      { type: 'created', text: 'Website form submission', at: daysAgo(40, 10) },
      { type: 'email', text: 'Quote sent', at: daysAgo(30, 10) },
      { type: 'status_change', text: 'Lost — competitor was cheaper', at: daysAgo(15, 11) },
    ],
  },
  {
    id: 'lead-022',
    name: 'Whitney Olusegun',
    phone: '(213) 335-9971',
    email: 'whitney.o@olumethod.com',
    vehicle: { year: 2023, make: 'Subaru', model: 'WRX' },
    serviceInterest: 'Roof Wrap',
    budget: 600,
    source: 'instagram',
    status: 'lost',
    priority: 'cold',
    assignee: null,
    tags: [],
    notes: 'Ghosted after quote.',
    followUpDate: null,
    createdAt: daysAgo(35, 10),
    lastContactedAt: daysAgo(20, 13),
    activities: [
      { type: 'created', text: 'Instagram inquiry', at: daysAgo(35, 10) },
      { type: 'email', text: 'Quote sent', at: daysAgo(28, 14) },
      { type: 'status_change', text: 'Marked as Lost — no response', at: daysAgo(20, 13) },
    ],
  },
  {
    id: 'lead-023',
    name: 'Franklin Vega',
    phone: '(626) 882-4400',
    email: 'franklin.vega@vegaauto.net',
    vehicle: { year: 2022, make: 'Chevy', model: 'Corvette' },
    serviceInterest: 'Ceramic Coating + Tint Combo',
    budget: 2100,
    source: 'carfax',
    status: 'lost',
    priority: 'warm',
    assignee: 'Daniel V.',
    tags: [],
    notes: 'Decided to wait until next year.',
    followUpDate: null,
    createdAt: daysAgo(50, 10),
    lastContactedAt: daysAgo(25, 10),
    activities: [
      { type: 'created', text: 'Lead from CarFax', at: daysAgo(50, 10) },
      { type: 'call', text: 'Consult', at: daysAgo(40, 13) },
      { type: 'status_change', text: 'Lost — postponed to next year', at: daysAgo(25, 10) },
    ],
  },
  {
    id: 'lead-024',
    name: 'Peter Huang',
    phone: '(408) 229-0044',
    email: 'peter.huang@northlight.co',
    vehicle: { year: 2023, make: 'Audi', model: 'Q8' },
    serviceInterest: 'Chrome Delete',
    budget: 2500,
    source: 'referral',
    status: 'lost',
    priority: 'cold',
    assignee: 'Chris M.',
    tags: ['Referral'],
    notes: 'Sold the vehicle.',
    followUpDate: null,
    createdAt: daysAgo(55, 10),
    lastContactedAt: daysAgo(30, 14),
    activities: [
      { type: 'created', text: 'Referral from Dan K.', at: daysAgo(55, 10) },
      { type: 'email', text: 'Quote sent', at: daysAgo(45, 13) },
      { type: 'status_change', text: 'Lost — customer sold vehicle', at: daysAgo(30, 14) },
    ],
  },
];

export const SEED_ESTIMATES = [
  {
    id: 'est-001', locationId: 'loc-001', estimateNumber: 'WM-0001',
    status: 'converted', customerId: 'c001', customerName: 'Marcus Bell',
    customerPhone: '(310) 555-0142', customerEmail: 'marcus.bell@email.com',
    vehicleId: 'v001', vehicleLabel: '2023 Tesla Model 3', vehicleVin: '5YJ3E1EA1PF123456',
    package: 'Full Wrap', material: '3M 1080 Series', materialColor: 'Matte Charcoal',
    laborHours: 18, basePrice: 2800, laborCost: 900, materialCost: 650, discount: 0, total: 4350,
    notes: 'Customer wants matte finish. Handle charge port area carefully.',
    createdBy: 'Alex R.', assignedTo: 'Jamie K.',
    createdAt: '2025-01-15T09:00:00Z', sentAt: '2025-01-16T10:00:00Z',
    expiresAt: '2025-02-15T00:00:00Z', approvedAt: '2025-01-20T14:00:00Z',
    declinedAt: null, convertedToInvoice: true, invoiceId: 'inv-0041',
  },
  {
    id: 'est-002', locationId: 'loc-001', estimateNumber: 'WM-0002',
    status: 'approved', customerId: 'c002', customerName: 'Devon Walsh',
    customerPhone: '(424) 555-0293', customerEmail: 'devon.walsh@email.com',
    vehicleId: 'v002', vehicleLabel: '2022 BMW M4', vehicleVin: 'WBS43AY01NCK98765',
    package: 'Full Wrap', material: 'Avery Dennison SW900', materialColor: 'Satin Black',
    laborHours: 20, basePrice: 3200, laborCost: 1000, materialCost: 720, discount: 150, total: 4770,
    notes: 'Full satin black, schedule confirmed.',
    createdBy: 'Jamie K.', assignedTo: 'Alex R.',
    createdAt: '2025-01-22T11:00:00Z', sentAt: '2025-01-23T09:30:00Z',
    expiresAt: '2025-02-22T00:00:00Z', approvedAt: '2025-01-25T16:45:00Z',
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-003', locationId: 'loc-001', estimateNumber: 'WM-0003',
    status: 'sent', customerId: 'c003', customerName: 'Tina Marsh',
    customerPhone: '(818) 555-0381', customerEmail: 'tina.marsh@email.com',
    vehicleId: 'v003', vehicleLabel: '2021 Ford F-150 Raptor', vehicleVin: '1FTFW1RG9MFC87321',
    package: 'Hood & Roof', material: '3M 2080 Series', materialColor: 'Gloss White',
    laborHours: 10, basePrice: 1400, laborCost: 500, materialCost: 380, discount: 0, total: 2280,
    notes: 'Partial roof + hood. Surface in good condition from prior removal.',
    createdBy: 'Sam T.', assignedTo: 'Sam T.',
    createdAt: '2025-02-10T08:00:00Z', sentAt: '2025-02-11T09:00:00Z',
    expiresAt: '2025-03-13T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-004', locationId: 'loc-001', estimateNumber: 'WM-0004',
    status: 'declined', customerId: 'c004', customerName: 'Kyle Huang',
    customerPhone: '(213) 555-0458', customerEmail: 'kyle.huang@email.com',
    vehicleId: 'v004', vehicleLabel: '2022 Porsche 911', vehicleVin: 'WP0AA2A99NS223344',
    package: 'Full Wrap', material: 'ORACAL 970RA', materialColor: 'Gloss Frozen Cherry',
    laborHours: 22, basePrice: 3600, laborCost: 1100, materialCost: 890, discount: 0, total: 5590,
    notes: 'Customer felt price was too high. Follow up in 30 days.',
    createdBy: 'Alex R.', assignedTo: 'Alex R.',
    createdAt: '2025-01-30T13:00:00Z', sentAt: '2025-01-31T10:00:00Z',
    expiresAt: '2025-03-01T00:00:00Z', approvedAt: null,
    declinedAt: '2025-02-05T17:30:00Z', convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-005', locationId: 'loc-001', estimateNumber: 'WM-0005',
    status: 'expired', customerId: 'c005', customerName: 'Jordan Lee',
    customerPhone: '(323) 555-0572', customerEmail: 'jordan.lee@email.com',
    vehicleId: 'v005', vehicleLabel: '2020 Jeep Wrangler', vehicleVin: '1C4HJXDG0LW123789',
    package: 'Partial Wrap', material: '3M 1080 Series', materialColor: 'Matte Military Green',
    laborHours: 12, basePrice: 1800, laborCost: 600, materialCost: 480, discount: 0, total: 2880,
    notes: 'Off-road accent graphics. Customer went silent after quote.',
    createdBy: 'Morgan L.', assignedTo: 'Morgan L.',
    createdAt: '2024-12-01T10:00:00Z', sentAt: '2024-12-02T11:00:00Z',
    expiresAt: '2025-01-01T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-006', locationId: 'loc-001', estimateNumber: 'WM-0006',
    status: 'draft', customerId: 'c006', customerName: 'Priya Nair',
    customerPhone: '(714) 555-0614', customerEmail: 'priya.nair@email.com',
    vehicleId: 'v006', vehicleLabel: '2024 Honda CR-V', vehicleVin: '7FARW2H50RE012345',
    package: 'Full Wrap', material: 'Avery Dennison SW900', materialColor: 'Gloss Cosmic Blue',
    laborHours: 16, basePrice: 2600, laborCost: 800, materialCost: 610, discount: 0, total: 4010,
    notes: 'Color change from silver to cosmic blue. Awaiting final approval from customer.',
    createdBy: 'Jamie K.', assignedTo: 'Jamie K.',
    createdAt: '2025-03-05T14:00:00Z', sentAt: null,
    expiresAt: '2025-04-05T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-007', locationId: 'loc-002', estimateNumber: 'WM-0007',
    status: 'sent', customerId: 'c007', customerName: 'Brett Tanaka',
    customerPhone: '(562) 555-0771', customerEmail: 'brett.tanaka@fleetco.com',
    vehicleId: 'v007', vehicleLabel: '2023 Ford Transit (Fleet)', vehicleVin: '1FTBR3X85PKA11111',
    package: 'Full Wrap', material: '3M 1080 Series', materialColor: 'Gloss White + Logo Overlay',
    laborHours: 24, basePrice: 4200, laborCost: 1200, materialCost: 980, discount: 420, total: 5960,
    notes: 'Fleet wrap — unit 1 of 4. Corporate branding with logo placement.',
    createdBy: 'Alex R.', assignedTo: 'Alex R.',
    createdAt: '2025-02-20T09:00:00Z', sentAt: '2025-02-21T08:30:00Z',
    expiresAt: '2025-03-23T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-008', locationId: 'loc-002', estimateNumber: 'WM-0008',
    status: 'approved', customerId: 'c007', customerName: 'Brett Tanaka',
    customerPhone: '(562) 555-0771', customerEmail: 'brett.tanaka@fleetco.com',
    vehicleId: 'v008', vehicleLabel: '2023 Ford Transit (Fleet)', vehicleVin: '1FTBR3X85PKA22222',
    package: 'Full Wrap', material: '3M 1080 Series', materialColor: 'Gloss White + Logo Overlay',
    laborHours: 24, basePrice: 4200, laborCost: 1200, materialCost: 980, discount: 420, total: 5960,
    notes: 'Fleet wrap — unit 2 of 4. Approved, pending scheduling.',
    createdBy: 'Alex R.', assignedTo: 'Alex R.',
    createdAt: '2025-02-20T09:05:00Z', sentAt: '2025-02-21T08:35:00Z',
    expiresAt: '2025-03-23T00:00:00Z', approvedAt: '2025-02-25T11:00:00Z',
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-009', locationId: 'loc-002', estimateNumber: 'WM-0009',
    status: 'draft', customerId: 'c007', customerName: 'Brett Tanaka',
    customerPhone: '(562) 555-0771', customerEmail: 'brett.tanaka@fleetco.com',
    vehicleId: 'v009', vehicleLabel: '2023 Ford Transit (Fleet)', vehicleVin: '1FTBR3X85PKA33333',
    package: 'Full Wrap', material: '3M 1080 Series', materialColor: 'Gloss White + Logo Overlay',
    laborHours: 24, basePrice: 4200, laborCost: 1200, materialCost: 980, discount: 420, total: 5960,
    notes: 'Fleet wrap — unit 3 of 4. Draft in progress.',
    createdBy: 'Alex R.', assignedTo: 'Alex R.',
    createdAt: '2025-03-01T10:00:00Z', sentAt: null,
    expiresAt: '2025-04-01T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-010', locationId: 'loc-002', estimateNumber: 'WM-0010',
    status: 'draft', customerId: 'c007', customerName: 'Brett Tanaka',
    customerPhone: '(562) 555-0771', customerEmail: 'brett.tanaka@fleetco.com',
    vehicleId: 'v010', vehicleLabel: '2023 Ford Transit (Fleet)', vehicleVin: '1FTBR3X85PKA44444',
    package: 'Full Wrap', material: '3M 1080 Series', materialColor: 'Gloss White + Logo Overlay',
    laborHours: 24, basePrice: 4200, laborCost: 1200, materialCost: 980, discount: 420, total: 5960,
    notes: 'Fleet wrap — unit 4 of 4. Not started yet.',
    createdBy: 'Alex R.', assignedTo: 'Unassigned',
    createdAt: '2025-03-01T10:10:00Z', sentAt: null,
    expiresAt: '2025-04-01T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-011', locationId: 'loc-002', estimateNumber: 'WM-0011',
    status: 'sent', customerId: 'c008', customerName: 'Destiny Monroe',
    customerPhone: '(626) 555-0832', customerEmail: 'destiny.monroe@email.com',
    vehicleId: 'v011', vehicleLabel: '2023 Audi RS5', vehicleVin: 'WUAPEWF58PA001122',
    package: 'Racing Stripes', material: 'ORACAL 651', materialColor: 'Gloss Neon Yellow',
    laborHours: 6, basePrice: 800, laborCost: 300, materialCost: 220, discount: 0, total: 1320,
    notes: 'Dual racing stripes hood to trunk. Customer wants precision placement.',
    createdBy: 'Sam T.', assignedTo: 'Sam T.',
    createdAt: '2025-03-10T15:00:00Z', sentAt: '2025-03-11T09:00:00Z',
    expiresAt: '2025-04-10T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
  {
    id: 'est-012', locationId: 'loc-002', estimateNumber: 'WM-0012',
    status: 'draft', customerId: 'c009', customerName: 'Sam Okafor',
    customerPhone: '(415) 555-0991', customerEmail: 'sam.okafor@email.com',
    vehicleId: 'v012', vehicleLabel: '2024 Dodge Challenger', vehicleVin: '2C3CDZBT5RH123456',
    package: 'Partial Wrap', material: 'Avery Dennison SW900', materialColor: 'Matte Carbon Fiber',
    laborHours: 14, basePrice: 2100, laborCost: 700, materialCost: 560, discount: 100, total: 3260,
    notes: 'Carbon fiber hood, roof, and trunk. Customer wants chrome delete too.',
    createdBy: 'Morgan L.', assignedTo: 'Morgan L.',
    createdAt: '2025-03-18T11:00:00Z', sentAt: null,
    expiresAt: '2025-04-18T00:00:00Z', approvedAt: null,
    declinedAt: null, convertedToInvoice: false, invoiceId: null,
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

function loadFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch { /* ignore */ }
  return SEED_ESTIMATES;
}

function saveToStorage(estimates) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(estimates)); } catch { /* ignore */ }
}

// ─── Context ─────────────────────────────────────────────────────────────────

const EstimateContext = createContext(null);

// ─── Provider ────────────────────────────────────────────────────────────────

export function EstimateProvider({ children }) {
  const { activeLocationId } = useLocations();
  const { orgId, org } = useAuth();

export const SEED_NOTIFICATIONS = [
  // ── UNREAD (8) ─────────────────────────────────────────────────────────────
  { id: 'notif-001', type: 'approval',  title: 'Estimate Approved',    body: 'Kyle Huang approved WM-0004 for $6,250',                                 link: 'estimates', recordId: 'est-002', read: false, createdAt: daysAgo(0, 1, 15), icon: 'check'   },
  { id: 'notif-002', type: 'overdue',   title: 'Invoice Overdue',      body: 'INV-0003 for Tina Marsh is 5 days overdue ($3,890)',                     link: 'invoices',  recordId: 'inv-003',  read: false, createdAt: daysAgo(0, 3, 40), icon: 'clock'   },
  { id: 'notif-003', type: 'lead',      title: 'Lead Assigned',         body: 'New lead from Instagram assigned to Jamie K.',                             link: 'leadhub',   recordId: null,     read: false, createdAt: daysAgo(1, 0, 30), icon: 'user'    },
  { id: 'notif-004', type: 'estimate',  title: 'Estimate Expiring Soon',body: 'WM-0007 for Chris Valdez expires in 2 days',                             link: 'estimates', recordId: 'est-007', read: false, createdAt: daysAgo(1, 5, 0),  icon: 'alert'   },
  { id: 'notif-005', type: 'payment',   title: 'Deposit Received',     body: 'Riley Carson paid $2,000 deposit on INV-0005',                            link: 'invoices',  recordId: 'inv-005', read: false, createdAt: daysAgo(2, 2, 10), icon: 'dollar'  },
  { id: 'notif-006', type: 'invoice',   title: 'Invoice Viewed',        body: 'Devon Walsh viewed INV-0002 ($2,150)',                                     link: 'invoices',  recordId: 'inv-002', read: false, createdAt: daysAgo(3, 0, 45), icon: 'document'},
  { id: 'notif-007', type: 'system',    title: 'Integration Connected',body: 'Carfax integration connected successfully',                             link: null,        recordId: null,     read: false, createdAt: daysAgo(4, 1, 0),  icon: 'bell'    },
  { id: 'notif-008', type: 'overdue',   title: 'Estimate Expired',    body: 'WM-0005 for Sandra Ortiz expired yesterday — follow up now',              link: 'estimates', recordId: 'est-005', read: false, createdAt: daysAgo(5, 8, 0),  icon: 'alert'   },
  // ── READ (7) ───────────────────────────────────────────────────────────────
  { id: 'notif-009', type: 'approval',  title: 'Estimate Approved',    body: 'Lisa Park approved WM-0003 for $8,900',                                 link: 'estimates', recordId: 'est-003', read: true,  createdAt: daysAgo(5, 10, 20), icon: 'check'   },
  { id: 'notif-010', type: 'lead',      title: 'New Lead Submitted',   body: 'Web form submission from Robert Diaz — full wrap inquiry',                link: 'leadhub',   recordId: null,     read: true,  createdAt: daysAgo(6, 3, 0),  icon: 'user'    },
  { id: 'notif-011', type: 'payment',   title: 'Payment Received',     body: 'Stephanie Nguyen paid $1,875 deposit on INV-0004',                        link: 'invoices',  recordId: 'inv-004', read: true,  createdAt: daysAgo(7, 0, 0),  icon: 'dollar'  },
  { id: 'notif-012', type: 'estimate',  title: 'Estimate Sent',        body: 'WM-0006 emailed to Jordan Lee for $5,600 — awaiting approval',            link: 'estimates', recordId: 'est-006', read: true,  createdAt: daysAgo(8, 2, 30), icon: 'document'},
  { id: 'notif-013', type: 'system',    title: 'Backup Complete',      body: 'Weekly data backup completed — all records secure',                      link: null,        recordId: null,     read: true,  createdAt: daysAgo(9, 6, 0),  icon: 'bell'    },
  { id: 'notif-014', type: 'invoice',   title: 'Invoice Paid in Full', body: 'INV-0005 for Anthony Reed marked as paid ($7,200)',                     link: 'invoices',  recordId: 'inv-005', read: true,  createdAt: daysAgo(11, 4, 15),icon: 'dollar'  },
  { id: 'notif-015', type: 'lead',      title: 'Lead Status Updated',   body: 'Maria Santos moved to "Proposal Sent" stage',                             link: 'leadhub',   recordId: null,     read: true,  createdAt: daysAgo(13, 9, 0), icon: 'user'    },
];

// ─── Storage helpers ──────────────────────────────────────────────────────────

const LS_KEY = 'wm-notifications-v1';

export const SEED_APPOINTMENTS = [
  {
    id: 'appt-001', locationId: 'loc-001',
    customerId: 'c001', customerName: 'Marcus Bell', customerPhone: '(310) 555-0142',
    vehicleLabel: '2023 Tesla Model 3',
    service: 'Full Wrap', estimateId: 'est-001', technicianId: 'tech-001',
    date: makeSeedDate(2), startTime: '09:00', endTime: '17:00',
    status: 'confirmed', type: 'appointment',
    notes: 'Handle charge port area carefully.',
    reminderQueued: true, reminderSent: false,
    reminderAt: new Date(Date.now() + 1 * 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'appt-002', locationId: 'loc-002',
    customerId: 'c002', customerName: 'Devon Walsh', customerPhone: '(424) 555-0293',
    vehicleLabel: '2022 BMW M4',
    service: 'Full Wrap', estimateId: 'est-002', technicianId: 'tech-002',
    date: makeSeedDate(5), startTime: '08:00', endTime: '18:00',
    status: 'scheduled', type: 'appointment',
    notes: '',
    reminderQueued: true, reminderSent: false,
    reminderAt: new Date(Date.now() + 4 * 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'appt-003', locationId: 'loc-001',
    customerId: 'c003', customerName: 'Tina Marsh', customerPhone: '(818) 555-0381',
    vehicleLabel: '2021 Ford F-150 Raptor',
    service: 'Hood & Roof', estimateId: 'est-003', technicianId: 'tech-003',
    date: makeSeedDate(7), startTime: '10:00', endTime: '12:00',
    status: 'scheduled', type: 'appointment',
    notes: 'Surface in good condition from prior wrap removal.',
    reminderQueued: true, reminderSent: false,
    reminderAt: new Date(Date.now() + 6 * 86400000).toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const SEED_TECHNICIANS = [
  { id: 'tech-001', name: 'Jamie K.', color: '#3B82F6', active: true },
  { id: 'tech-002', name: 'Alex R.',  color: '#8B5CF6', active: true },
  { id: 'tech-003', name: 'Sam T.',   color: '#10B981', active: true },
];

// ─── Storage helpers ─────────────────────────────────────────────────────────

function loadFromStorage(key, fallback) {
  try {
    const raw = localStorage.getItem(key);
    if (raw) { const p = JSON.parse(raw); if (Array.isArray(p) && p.length > 0) return p; }
  } catch { /* ignore */ }
  return fallback;
}

function saveToStorage(key, value) {
  try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* ignore */ }
}

// ─── Context ─────────────────────────────────────────────────────────────────

const SchedulingContext = createContext(null);

export const SEED_EMPLOYEES = [
  { id: 'e1', name: 'Tavo R.',   initials: 'TR', role: 'Lead Installer', color: '#2E8BF0', isActive: true },
  { id: 'e2', name: 'Maria L.',  initials: 'ML', role: 'Estimator',      color: '#8B5CF6', isActive: true },
  { id: 'e3', name: 'Daniel V.', initials: 'DV', role: 'Installer',     color: '#22C55E', isActive: true },
  { id: 'e4', name: 'Chris M.',  initials: 'CM', role: 'Sales',         color: '#F59E0B', isActive: true },
];

export const SEED_EVENTS = [
  { id: 'ev1',  employeeId: 'e1', achievementId: 'full_wrap_sold',     xp: 150, note: 'Ram 1500 full wrap',         awardedBy: 'system', timestamp: daysAgo(28) },
  { id: 'ev2',  employeeId: 'e1', achievementId: 'estimate_created',   xp: 10,  note: '',                             awardedBy: 'system', timestamp: daysAgo(25) },
  { id: 'ev3',  employeeId: 'e1', achievementId: 'estimate_approved',  xp: 25,  note: 'Cyber Monday deal approved',   awardedBy: 'system', timestamp: daysAgo(22) },
  { id: 'ev4',  employeeId: 'e1', achievementId: 'lead_converted',     xp: 75,  note: 'Fleet client closed',          awardedBy: 'system', timestamp: daysAgo(18) },
  { id: 'ev5',  employeeId: 'e1', achievementId: 'five_star_review',  xp: 150, note: 'Google review from Torres',    awardedBy: 'owner',  timestamp: daysAgo(10) },
  { id: 'ev6',  employeeId: 'e1', achievementId: 'perfect_week',      xp: 200, note: '',                             awardedBy: 'system', timestamp: daysAgo(5)  },
  { id: 'ev7',  employeeId: 'e2', achievementId: 'estimate_created',   xp: 10,  note: '',                             awardedBy: 'system', timestamp: daysAgo(27) },
  { id: 'ev8',  employeeId: 'e2', achievementId: 'estimate_approved',  xp: 25,  note: 'Sprinter wrap approved',       awardedBy: 'system', timestamp: daysAgo(24) },
  { id: 'ev9',  employeeId: 'e2', achievementId: 'ten_estimates_week',xp: 100, note: '12 estimates in one week!',   awardedBy: 'system', timestamp: daysAgo(20) },
  { id: 'ev10', employeeId: 'e2', achievementId: 'upsell_closed',     xp: 100, note: 'Added window tint upsell',     awardedBy: 'system', timestamp: daysAgo(14) },
  { id: 'ev11', employeeId: 'e2', achievementId: 'referral',          xp: 50,  note: 'Referred by Garcia family',    awardedBy: 'system', timestamp: daysAgo(8)  },
  { id: 'ev12', employeeId: 'e2', achievementId: 'manual_bonus',      xp: 75,  note: 'Great attitude this month',    awardedBy: 'owner',  timestamp: daysAgo(3)  },
  { id: 'ev13', employeeId: 'e3', achievementId: 'estimate_created',   xp: 10,  note: '',                             awardedBy: 'system', timestamp: daysAgo(26) },
  { id: 'ev14', employeeId: 'e3', achievementId: 'estimate_approved', xp: 25,  note: 'Tacoma partial approved',      awardedBy: 'system', timestamp: daysAgo(21) },
  { id: 'ev15', employeeId: 'e3', achievementId: 'lead_converted',    xp: 75,  note: 'Walk-in converted same day',   awardedBy: 'system', timestamp: daysAgo(16) },
  { id: 'ev16', employeeId: 'e3', achievementId: 'first_job_day',     xp: 5,   note: 'Logged at 8:42 AM',           awardedBy: 'system', timestamp: daysAgo(12) },
  { id: 'ev17', employeeId: 'e3', achievementId: 'referral',          xp: 50,  note: 'Referral from Hernandez',      awardedBy: 'system', timestamp: daysAgo(7)  },
  { id: 'ev18', employeeId: 'e4', achievementId: 'estimate_created',  xp: 10,  note: '',                             awardedBy: 'system', timestamp: daysAgo(29) },
  { id: 'ev19', employeeId: 'e4', achievementId: 'upsell_closed',     xp: 100, note: 'PPF package upsell',           awardedBy: 'system', timestamp: daysAgo(23) },
  { id: 'ev20', employeeId: 'e4', achievementId: 'revenue_milestone', xp: 200, note: 'Hit $5k on Friday!',           awardedBy: 'system', timestamp: daysAgo(17) },
  { id: 'ev21', employeeId: 'e4', achievementId: 'estimate_approved', xp: 25,  note: 'Tesla Model Y approved',        awardedBy: 'system', timestamp: daysAgo(11) },
  { id: 'ev22', employeeId: 'e4', achievementId: 'first_job_day',    xp: 5,   note: 'First in at 8:15 AM',         awardedBy: 'system', timestamp: daysAgo(4)  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function computeLevel(totalXP) {
  let current = LEVELS[0];
  let next = LEVELS[1] || null;
  for (let i = LEVELS.length - 1; i >= 0; i--) {
    if (totalXP >= LEVELS[i].minXP) {
      current = LEVELS[i];
      next = LEVELS[i + 1] || null;
      break;
    }
  }
  const xpToNext = next ? next.minXP - totalXP : 0;
  const rangeStart = current.minXP;
  const rangeEnd = next ? next.minXP : current.minXP;
  const progressPct = next
    ? Math.min(100, Math.round(((totalXP - rangeStart) / (rangeEnd - rangeStart)) * 100))
    : 100;
  return { level: current, nextLevel: next, xpToNext, progressPct };
}

function startOfWeek() {
  const d = new Date();
  const day = d.getDay();
  d.setDate(d.getDate() - day);
  d.setHours(0, 0, 0, 0);
  return d;
}

function startOfMonth() {
  const d = new Date();
  d.setDate(1);
  d.setHours(0, 0, 0, 0);
  return d;
}

// ─── Reducer ──────────────────────────────────────────────────────────────────

const initialState = {
  employees: [],
  events: [],
};

export const SEED_LOCATIONS = [
  {
    id: 'loc-001',
    name: 'Main Street Shop',
    address: '3129 Main St',
    city: 'West Hollywood',
    state: 'CA',
    zip: '90046',
    phone: '(310) 555-0100',
    color: '#2E8BF0',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'loc-002',
    name: 'Downtown Studio',
    address: '800 S Figueroa St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90017',
    phone: '(213) 555-0200',
    color: '#10B981',
    createdAt: '2024-06-01T00:00:00Z',
  },
];

export const SEED_INVOICES = [
  {
    id: 'inv-001', locationId: 'loc-001', invoiceNumber: 'INV-0001',
    estimateId: 'est-003', estimateNumber: 'WM-0003',
    status: 'paid',
    customerId: 'c001', customerName: 'Marcus Bell',
    customerEmail: 'marcus.bell@email.com', customerPhone: '(310) 555-0192',
    vehicleLabel: '2023 Tesla Model 3',
    lineItems: [
      { id: 'li-1', description: 'Full Body Wrap – 3M 1080 Matte Charcoal', qty: 1, unit: 'job', unitPrice: 2800, total: 2800 },
      { id: 'li-2', description: 'Labor – Installation (18 hrs @ $50/hr)', qty: 18, unit: 'hr', unitPrice: 50, total: 900 },
      { id: 'li-3', description: 'Ceramic Coating Add-on', qty: 1, unit: 'job', unitPrice: 350, total: 350 },
    ],
    subtotal: 4050, taxRate: TAX_RATE, taxAmount: 354.38, discount: 0,
    total: 4404.38, amountPaid: 4404.38, amountDue: 0,
    payments: [
      { id: 'pay-001', method: 'Card', amount: 2000, note: 'Deposit', recordedAt: '2025-01-21T14:00:00Z', recordedBy: 'Alex R.' },
      { id: 'pay-002', method: 'Card', amount: 2404.38, note: 'Balance – pickup', recordedAt: '2025-02-01T10:30:00Z', recordedBy: 'Alex R.' },
    ],
    notes: 'Net 15 terms. Full payment due before vehicle is released.',
    terms: 'Net 15',
    issuedAt: '2025-01-20T09:00:00Z', dueAt: '2025-02-04T00:00:00Z',
    paidAt: '2025-02-01T10:30:00Z', voidedAt: null,
    createdBy: 'Alex R.',
  },
  {
    id: 'inv-002', locationId: 'loc-001', invoiceNumber: 'INV-0002',
    estimateId: 'est-007', estimateNumber: 'WM-0007',
    status: 'paid',
    customerId: 'c002', customerName: 'Devon Walsh',
    customerEmail: 'devon.walsh@email.com', customerPhone: '(424) 555-0341',
    vehicleLabel: '2022 BMW M4 Competition',
    lineItems: [
      { id: 'li-1', description: 'Partial Wrap – Hood & Roof – Avery Dennison Gloss Black', qty: 1, unit: 'job', unitPrice: 1400, total: 1400 },
      { id: 'li-2', description: 'Paint Protection Film – Front Bumper', qty: 1, unit: 'job', unitPrice: 650, total: 650 },
      { id: 'li-3', description: 'Labor – 8 hrs', qty: 8, unit: 'hr', unitPrice: 50, total: 400 },
    ],
    subtotal: 2450, taxRate: TAX_RATE, taxAmount: 214.38, discount: 100,
    total: 2564.38, amountPaid: 2564.38, amountDue: 0,
    payments: [
      { id: 'pay-003', method: 'Zelle', amount: 2564.38, note: 'Paid in full', recordedAt: '2025-02-10T09:15:00Z', recordedBy: 'Alex R.' },
    ],
    notes: 'Returning customer – 5% loyalty discount applied.',
    terms: 'Due on Receipt',
    issuedAt: '2025-02-08T10:00:00Z', dueAt: '2025-02-08T00:00:00Z',
    paidAt: '2025-02-10T09:15:00Z', voidedAt: null,
    createdBy: 'Alex R.',
  },
  {
    id: 'inv-003', locationId: 'loc-001', invoiceNumber: 'INV-0003',
    estimateId: 'est-011', estimateNumber: 'WM-0011',
    status: 'partial',
    customerId: 'c003', customerName: 'Tina Marsh',
    customerEmail: 'tina.marsh@email.com', customerPhone: '(213) 555-0887',
    vehicleLabel: '2024 Porsche Cayenne',
    lineItems: [
      { id: 'li-1', description: 'Full Body Wrap – Satin Midnight Blue', qty: 1, unit: 'job', unitPrice: 3600, total: 3600 },
      { id: 'li-2', description: 'Window Tint – All Windows', qty: 1, unit: 'job', unitPrice: 480, total: 480 },
      { id: 'li-3', description: 'Labor – 22 hrs', qty: 22, unit: 'hr', unitPrice: 50, total: 1100 },
    ],
    subtotal: 5180, taxRate: TAX_RATE, taxAmount: 453.25, discount: 0,
    total: 5633.25, amountPaid: 2000, amountDue: 3633.25,
    payments: [
      { id: 'pay-004', method: 'Check', amount: 2000, note: '50% deposit at drop-off', recordedAt: '2025-03-05T11:00:00Z', recordedBy: 'Jordan L.' },
    ],
    notes: 'Balance due upon completion.',
    terms: 'Net 30',
    issuedAt: '2025-03-04T09:00:00Z', dueAt: '2025-04-03T00:00:00Z',
    paidAt: null, voidedAt: null,
    createdBy: 'Jordan L.',
  },
  {
    id: 'inv-004', locationId: 'loc-001', invoiceNumber: 'INV-0004',
    estimateId: 'est-015', estimateNumber: 'WM-0015',
    status: 'partial',
    customerId: 'c004', customerName: 'Kyle Huang',
    customerEmail: 'kyle.huang@email.com', customerPhone: '(626) 555-0123',
    vehicleLabel: '2021 Toyota Tacoma TRD',
    lineItems: [
      { id: 'li-1', description: 'Roof & Pillars Wrap – Gloss Black', qty: 1, unit: 'job', unitPrice: 900, total: 900 },
      { id: 'li-2', description: 'Hood Wrap – Matte Gunmetal', qty: 1, unit: 'job', unitPrice: 750, total: 750 },
      { id: 'li-3', description: 'Rear Bumper Guard Film', qty: 1, unit: 'job', unitPrice: 320, total: 320 },
      { id: 'li-4', description: 'Labor – 12 hrs', qty: 12, unit: 'hr', unitPrice: 50, total: 600 },
    ],
    subtotal: 2570, taxRate: TAX_RATE, taxAmount: 224.88, discount: 0,
    total: 2794.88, amountPaid: 1500, amountDue: 1294.88,
    payments: [
      { id: 'pay-005', method: 'Cash', amount: 1500, note: 'Deposit at booking', recordedAt: '2025-03-10T16:00:00Z', recordedBy: 'Sam T.' },
    ],
    notes: 'Split payment — remaining balance on completion.',
    terms: 'Net 15',
    issuedAt: '2025-03-09T09:00:00Z', dueAt: '2025-03-24T00:00:00Z',
    paidAt: null, voidedAt: null,
    createdBy: 'Sam T.',
  },
  {
    id: 'inv-005', locationId: 'loc-001', invoiceNumber: 'INV-0005',
    estimateId: 'est-017', estimateNumber: 'WM-0017',
    status: 'sent',
    customerId: 'c005', customerName: 'Riley Carson',
    customerEmail: 'riley.carson@email.com', customerPhone: '(818) 555-0277',
    vehicleLabel: '2022 Mercedes-AMG GT',
    lineItems: [
      { id: 'li-1', description: 'Full Body Wrap – ORACAL 970RA Satin Pearl White', qty: 1, unit: 'job', unitPrice: 3100, total: 3100 },
      { id: 'li-2', description: 'Chrome Delete – Window Trim', qty: 1, unit: 'job', unitPrice: 280, total: 280 },
      { id: 'li-3', description: 'Labor – 16 hrs', qty: 16, unit: 'hr', unitPrice: 50, total: 800 },
    ],
    subtotal: 4180, taxRate: TAX_RATE, taxAmount: 365.75, discount: 0,
    total: 4545.75, amountPaid: 0, amountDue: 4545.75,
    payments: [],
    notes: 'Sent for review. Awaiting customer confirmation.',
    terms: 'Due on Receipt',
    issuedAt: '2025-03-18T10:00:00Z', dueAt: '2025-04-02T00:00:00Z',
    paidAt: null, voidedAt: null,
    createdBy: 'Alex R.',
  },
  {
    id: 'inv-006', locationId: 'loc-001', invoiceNumber: 'INV-0006',
    estimateId: 'est-019', estimateNumber: 'WM-0019',
    status: 'overdue',
    customerId: 'c005', customerName: 'Avery Nguyen',
    customerEmail: 'avery.nguyen@email.com', customerPhone: '(714) 555-0443',
    vehicleLabel: '2023 Rivian R1T',
    lineItems: [
      { id: 'li-1', description: 'Full Body Wrap – 3M 2080 Satin Military Green', qty: 1, unit: 'job', unitPrice: 3300, total: 3300 },
      { id: 'li-2', description: 'Bedliner Protection Film', qty: 1, unit: 'job', unitPrice: 420, total: 420 },
      { id: 'li-3', description: 'Labor – 18 hrs', qty: 18, unit: 'hr', unitPrice: 50, total: 900 },
    ],
    subtotal: 4620, taxRate: TAX_RATE, taxAmount: 404.25, discount: 200,
    total: 4824.25, amountPaid: 0, amountDue: 4824.25,
    payments: [],
    notes: 'Past due — sent two reminder emails.',
    terms: 'Net 15',
    issuedAt: '2025-02-01T09:00:00Z', dueAt: '2025-02-16T00:00:00Z',
    paidAt: null, voidedAt: null,
    createdBy: 'Morgan L.',
  },
  {
    id: 'inv-007', locationId: 'loc-002', invoiceNumber: 'INV-0007',
    estimateId: 'est-021', estimateNumber: 'WM-0021',
    status: 'paid',
    customerId: 'c006', customerName: 'Cameron Poe',
    customerEmail: 'cameron.poe@fleetlogistics.com', customerPhone: '(949) 555-0556',
    vehicleLabel: '2023 Ford Transit (Fleet)',
    lineItems: [
      { id: 'li-1', description: 'Full Fleet Wrap – 4 Units – Gloss White + Branding', qty: 4, unit: 'units', unitPrice: 3800, total: 15200 },
      { id: 'li-2', description: 'Logo Design & Print Setup', qty: 1, unit: 'flat', unitPrice: 600, total: 600 },
      { id: 'li-3', description: 'Labor – 96 hrs total (24/unit)', qty: 96, unit: 'hr', unitPrice: 50, total: 4800 },
    ],
    subtotal: 20600, taxRate: TAX_RATE, taxAmount: 1802.50, discount: 500,
    total: 21902.50, amountPaid: 21902.50, amountDue: 0,
    payments: [
      { id: 'pay-006', method: 'Wire', amount: 21902.50, note: 'Full payment – wire transfer', recordedAt: '2025-03-01T12:00:00Z', recordedBy: 'Alex R.' },
    ],
    notes: 'Fleet wrap project – units delivered and approved.',
    terms: 'Net 30',
    issuedAt: '2025-02-25T09:00:00Z', dueAt: '2025-03-27T00:00:00Z',
    paidAt: '2025-03-01T12:00:00Z', voidedAt: null,
    createdBy: 'Alex R.',
  },
  {
    id: 'inv-008', locationId: 'loc-002', invoiceNumber: 'INV-0008',
    estimateId: 'est-023', estimateNumber: 'WM-0023',
    status: 'partial',
    customerId: 'c006', customerName: 'Cameron Poe',
    customerEmail: 'cameron.poe@fleetlogistics.com', customerPhone: '(949) 555-0556',
    vehicleLabel: '2023 Ford E-Transit (Fleet)',
    lineItems: [
      { id: 'li-1', description: 'Full Fleet Wrap – 3 Units – Gloss White + Branding', qty: 3, unit: 'units', unitPrice: 3600, total: 10800 },
      { id: 'li-2', description: 'EV Decal Package – Charge Port & Trim', qty: 3, unit: 'units', unitPrice: 180, total: 540 },
      { id: 'li-3', description: 'Labor – 72 hrs total (24/unit)', qty: 72, unit: 'hr', unitPrice: 50, total: 3600 },
    ],
    subtotal: 14940, taxRate: TAX_RATE, taxAmount: 1307.25, discount: 0,
    total: 16247.25, amountPaid: 8000, amountDue: 8247.25,
    payments: [
      { id: 'pay-007', method: 'ACH', amount: 8000, note: '50% deposit', recordedAt: '2025-03-12T10:00:00Z', recordedBy: 'Alex R.' },
    ],
    notes: 'Fleet EV wrap – in progress, remaining balance due on completion.',
    terms: 'Net 30',
    issuedAt: '2025-03-10T09:00:00Z', dueAt: '2025-04-09T00:00:00Z',
    paidAt: null, voidedAt: null,
    createdBy: 'Alex R.',
  },
  {
    id: 'inv-009', locationId: 'loc-002', invoiceNumber: 'INV-0009',
    estimateId: 'est-038', estimateNumber: 'WM-0038',
    status: 'draft',
    customerId: 'c008', customerName: 'Sam Okafor',
    customerEmail: 'sam.okafor@email.com', customerPhone: '(562) 555-0884',
    vehicleLabel: '2024 Ram 1500 TRX',
    lineItems: [
      { id: 'li-1', description: 'Full Body Wrap – Matte Army Green', qty: 1, unit: 'job', unitPrice: 3800, total: 3800 },
      { id: 'li-2', description: 'Blackout Package – Emblems & Trim', qty: 1, unit: 'job', unitPrice: 450, total: 450 },
      { id: 'li-3', description: 'Labor – 20 hrs', qty: 20, unit: 'hr', unitPrice: 50, total: 1000 },
    ],
    subtotal: 5250, taxRate: TAX_RATE, taxAmount: 459.38, discount: 0,
    total: 5709.38, amountPaid: 0, amountDue: 5709.38,
    payments: [],
    notes: 'Pending customer approval of wrap sample colors.',
    terms: 'Net 15',
    issuedAt: '2025-04-08T14:00:00Z', dueAt: '2025-04-23T00:00:00Z',
    paidAt: null, voidedAt: null,
    createdBy: 'Alex R.',
  },
  {
    id: 'inv-010', locationId: 'loc-002', invoiceNumber: 'INV-0010',
    estimateId: 'est-041', estimateNumber: 'WM-0041',
    status: 'voided',
    customerId: 'c009', customerName: 'Morgan Reyes',
    customerEmail: 'morgan.reyes@email.com', customerPhone: '(949) 555-0601',
    vehicleLabel: '2019 Jeep Wrangler Unlimited',
    lineItems: [
      { id: 'li-1', description: 'Full Body Wrap – Digital Camo Pattern', qty: 1, unit: 'job', unitPrice: 3100, total: 3100 },
      { id: 'li-2', description: 'Labor – 17 hrs', qty: 17, unit: 'hr', unitPrice: 50, total: 850 },
    ],
    subtotal: 3950, taxRate: TAX_RATE, taxAmount: 345.63, discount: 0,
    total: 4295.63, amountPaid: 0, amountDue: 4295.63,
    payments: [],
    notes: 'Voided – customer cancelled project before start.',
    terms: 'Net 30',
    issuedAt: '2025-02-14T09:00:00Z', dueAt: '2025-03-16T00:00:00Z',
    paidAt: null, voidedAt: '2025-02-16T11:30:00Z',
    createdBy: 'Alex R.',
  },
];

// ─── Storage helpers ──────────────────────────────────────────────────────────

function loadFromStorage() {
  try {
    const raw = localStorage.getItem(LS_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) return parsed;
    }
  } catch { /* ignore */ }
  return SEED_INVOICES;
}

function saveToStorage(invoices) {
  try { localStorage.setItem(LS_KEY, JSON.stringify(invoices)); } catch { /* ignore */ }
}

// ─── Context ─────────────────────────────────────────────────────────────────

const InvoiceContext = createContext(null);

