export const SEED_NOTIFICATIONS = [
  // ── UNREAD (8) ─────────────────────────────────────────────────────────────
  { id: 'notif-001', type: 'approval',  title: 'Estimate Approved',    body: 'Kyle Huang approved WM-0004 for $6,250',                                 link: 'estimates', recordId: 'est-002', read: false, createdAt: daysAgo(0, 1, 15), icon: 'check'   },
  { id: 'notif-002', type: 'overdue',   title: 'Invoice Overdue',      body: 'INV-0003 for Tina Marsh is 5 days overdue ($3,890)',                     link: 'invoices',  recordId: 'inv-003',  read: false, createdAt: daysAgo(0, 3, 40), icon: 'clock'   },
  { id: 'notif-003', type: 'lead',      title: 'Lead Assigned',         body: 'New lead from Instagram assigned to Jamie K.',                             link: 'leadhub',   recordId: null,     read: false, createdAt: daysAgo(1, 0, 30), icon: 'user'    },
  { id: 'notif-004', type: 'estimate',  title: 'Estimate Expiring Soon',body: 'WM-0007 for Chris Valdez expires in 2 days',                             link: 'estimates', recordId: 'est-007', read: false, createdAt: daysAgo(1, 5, 0),  icon: 'alert'   },
  { id: 'notif-005', type: 'payment',   title: 'Deposit Received',     body: 'Riley Carson paid $2,000 deposit on INV-0005',                            link: 'invoices',  recordId: 'inv-005', read: false, createdAt: daysAgo(2, 2, 10), icon: 'dollar'  },
  { id: 'notif-006', type: 'invoice',   title: 'Invoice Viewed',        body: 'Devon Walsh viewed INV-0002 ($2,150)',                                     link: 'invoices',  recordId: 'inv-002', read: false, createdAt: daysAgo(3, 0, 45), icon: 'document'},
  { id: 'notif-007', type: 'system',    title: 'Integration Connected',body: 'Carfax integration connected successfully',                             link: null,        recordId: null,     read: false, createdAt: daysAgo(4, 1, 0),  icon: 'bell'    },
  { id: 'notif-008', type: 'overdue',   title: 'Estimate Expired',    body: 'WM-0005 for Sandra Ortiz expired yesterday — follow up now',              link: 'estimates', recordId: 'est-005', read: false, createdAt: daysAgo(5, 8, 0),  icon: 'alert'   },
  // ── READ (7) ───────────────────────────────────────────────────────────────
  { id: 'notif-009', type: 'approval',  title: 'Estimate Approved',    body: 'Lisa Park approved WM-0003 for $8,900',                                 link: 'estimates', recordId: 'est-003', read: true,  createdAt: daysAgo(5, 10, 20), icon: 'check'   },
  { id: 'notif-010', type: 'lead',      title: 'New Lead Submitted',   body: 'Web form submission from Robert Diaz — full wrap inquiry',                link: 'leadhub',   recordId: null,     read: true,  createdAt: daysAgo(6, 3, 0),  icon: 'user'    },
  { id: 'notif-011', type: 'payment',   title: 'Payment Received',     body: 'Stephanie Nguyen paid $1,875 deposit on INV-0004',                        link: 'invoices',  recordId: 'inv-004', read: true,  createdAt: daysAgo(7, 0, 0),  icon: 'dollar'  },
  { id: 'notif-012', type: 'estimate',  title: 'Estimate Sent',        body: 'WM-0006 emailed to Jordan Lee for $5,600 — awaiting approval',            link: 'estimates', recordId: 'est-006', read: true,  createdAt: daysAgo(8, 2, 30), icon: 'document'},
  { id: 'notif-013', type: 'system',    title: 'Backup Complete',      body: 'Weekly data backup completed — all records secure',                      link: null,        recordId: null,     read: true,  createdAt: daysAgo(9, 6, 0),  icon: 'bell'    },
  { id: 'notif-014', type: 'invoice',   title: 'Invoice Paid in Full', body: 'INV-0005 for Anthony Reed marked as paid ($7,200)',                     link: 'invoices',  recordId: 'inv-005', read: true,  createdAt: daysAgo(11, 4, 15),icon: 'dollar'  },
  { id: 'notif-015', type: 'lead',      title: 'Lead Status Updated',   body: 'Maria Santos moved to "Proposal Sent" stage',                             link: 'leadhub',   recordId: null,     read: true,  createdAt: daysAgo(13, 9, 0), icon: 'user'    },
];
